#!/usr/bin/env python3
"""Mnemotechnické obrazy ke všem 136 zkouškovým otázkám z farmakologie.

Každý zápis `S(...)` = jedna strana atlasu `MNEMO.pdf`:
  hak     — věta, která se má vybavit jako první
  panely  — 3–4 dvojice (glyf, popisek): obrázkový příběh zleva doprava
  rozklic — dvojice (co vidíš, co to doopravdy znamená) → převod obrazu na fakt
  past    — nejčastější omyl u téhle otázky

⚠️ **Mnemotechnika nesmí zakódovat nepravdu.** Chybný hák se naučí stejně
pevně jako správný a u zkoušky vypadne jako omyl. Proto je pravidlo: obraz smí
být přehnaný a absurdní, ale **rozklíčování se píše odborně a doslova**.

Přegeneruje se příkazem `python3 nastroje/gen_mnemo.py`.
"""
from mnemo import scena

O = []


def S(cislo, nadpis, hak, panely, rozklic, past=None):
    O.append((cislo, nadpis, scena(cislo, nadpis, hak, panely, rozklic, past)))


# ───────────────────────────────── OBECNÁ FARMAKOLOGIE ─────────────────────────

S("O1", "Farmakologie, původ a zdroje léčiv, názvy, lékopis",
  "Kinetika = KAM lék jde. Dynamika = CO tam dělá. Jedna cesta tam, druhá zpátky.",
  [("🧭", "KINETIKA: co dělá tělo s lékem"),
   ("💥", "DYNAMIKA: co dělá lék s tělem"),
   ("🌿", "Zdroje: rostlina, zvíře, mikrob, syntéza, biotechnologie"),
   ("📕", "LÉKOPIS: závazný předpis jakosti")],
  [("Kompas", "Farmakokinetika — absorpce, distribuce, metabolismus, exkrece (ADME)."),
   ("Výbuch", "Farmakodynamika — mechanismus účinku, vztah dávky a odpovědi."),
   ("Bylina a bakterie", "Zdroje: rostliny (morfin, atropin, digoxin), živočichové (heparin, inzulin), mikroorganismy (peniciliny), chemická syntéza, biotechnologie (monoklonální protilátky)."),
   ("Tři jména", "Chemický (vzorec) · generický = mezinárodní nechráněný (ibuprofen) · firemní chráněný (Brufen®)."),
   ("Červená kniha", "Lékopis — závazný soubor požadavků na jakost léčiv; Český vychází z Evropského.")],
  "Léčivá látka je nositel účinku; léčivý přípravek je hotová forma, kterou pacient dostane. Magistraliter se připravuje v lékárně, HVLP se vyrábí hromadně.")

S("O2", "Legislativa, doplňky stravy, zdravotnické prostředky, regulační orgány",
  "Lék musí DOKÁZAT, že funguje. Doplněk stravy jen nesmí LHÁT, že léčí. O kategorii rozhoduje mechanismus, ne složení.",
  [("⚖️", "LÉK: prokáže účinnost, bezpečnost, jakost"),
   ("🥤", "DOPLNĚK: právně potravina, stačí ohlášení"),
   ("🩹", "PROSTŘEDEK: působí FYZIKÁLNĚ"),
   ("🏛️", "SÚKL · EMA · SZPI")],
  [("Váhy", "Léčivý přípravek působí farmakologicky, imunologicky nebo metabolicky; registruje SÚKL národně nebo EMA centralizovaně."),
   ("Kelímek", "Doplněk stravy je potravina — účinnost dokládat nemusí, nesmí tvrdit, že léčí; dozor má SZPI."),
   ("Náplast", "Zdravotnický prostředek působí fyzikálně (výplň, implantát, obvaz) — posuzuje se shoda a riziková třída."),
   ("Budova", "SÚKL registruje, stanovuje ceny a úhrady, dozoruje lékárny a vede farmakovigilanci; klinické hodnocení schvaluje i etická komise.")],
  "Pacient rozdíl mezi lékem a doplňkem nevidí — na doplňky se proto ptej cíleně: mají reálné interakce (třezalka, ginkgo, česnek).")

S("O3", "Předepisování léčivých přípravků",
  "Recept je PRÁVNÍ dokument dvou lidí: lékař ručí za to, co předepsal, lékárník za to, co vydal.",
  [("💻", "eRecept: identifikátor do centrálního úložiště"),
   ("✍️", "Rp. — složení — M.f. — D.S."),
   ("🟦", "MODRÝ PRUH: omamné a psychotropní"),
   ("🔁", "Opakovací recept: uvádí počet opakování")],
  [("Dva podpisy", "Odpovědnost je sdílená — proto musí být recept čitelný a úplný."),
   ("Náležitosti", "Pacient (jméno, číslo pojištěnce) · léčivo (název, síla, forma, množství) · dávkování a způsob podání (D.S. = da signa) · lékař a pracoviště s podpisem a razítkem · datum."),
   ("Modrý pruh", "Vyhrazen omamným a psychotropním látkám, má přísnější evidenci."),
   ("Rp. = recipe", "„Vezmi“; M.f. = misce fiat („smíchej, ať vznikne“); D.S. = „vydej a označ“ — stavba magistraliter předpisu.")],
  "Platnost běžného receptu je zpravidla 14 dní, u antibiotik kratší [ověřit dle skript]. Před předepsáním patří anamnéza: alergie, gravidita, funkce jater a ledvin, ostatní léky.")

S("O4", "Preklinické a klinické hodnocení léčiv",
  "I. je to bezpečné? II. jaká dávka? III. je to lepší než dosavadní léčba? IV. co vzácného se objeví, až to bere milion lidí?",
  [("🐁", "PREKLINIKA: in vitro a na zvířeti"),
   ("💪", "I. desítky ZDRAVÝCH — bezpečnost"),
   ("🧪", "II. stovky nemocných — dávka · III. tisíce — srovnání"),
   ("🌍", "IV. běžná populace — vzácné nežádoucí účinky")],
  [("Myš", "Preklinika: farmakokinetika, farmakodynamika, toxicita (ED50, TD50, LD50), mutagenita, teratogenita, karcinogenita."),
   ("Fáze I", "Desítky zdravých dobrovolníků — snášenlivost a chování látky v těle; zahajuje se mikrodávkami s pomalou eskalací."),
   ("Fáze II a III", "II. stovky nemocných — hledá se účinná dávka. III. tisíce — srovnání s dosavadní léčbou nebo placebem; na jejím základě se registruje."),
   ("Fáze IV", "Po uvedení na trh — sledování v běžné populaci; teprve tady se odhalí vzácné nežádoucí účinky, protože ve studii na tisících pacientů neměly šanci vyjít najevo."),
   ("Zásady studie", "Randomizace, zaslepení (jednoduché, dvojité, trojité), kontrolní skupina, předem daný cíl, souhlas etické komise.")],
  "Generikum účinnost neprokazuje znovu — dokládá bioekvivalenci, tedy shodný průběh hladin s originálem.")

S("O5", "Způsoby aplikace léčiv, výhody a nevýhody",
  "Hlavní otázka není „jak rychle“, ale „PROJDE TO JÁTRY?“. First-pass obchází: pod jazyk, do žíly, do svalu, na kůži.",
  [("🚪", "PERORÁLNĚ: projde játry, first-pass"),
   ("👅", "SUBLINGVÁLNĚ: obchází játra — nitroglycerin"),
   ("💉", "I.V.: okamžitě, F = 100 %, nevratné"),
   ("🩹", "TRANSDERMÁLNĚ: nejpomalejší, účinek dny")],
  [("Dveře do jater", "Perorální podání = vrátnice: látka projde střevní stěnou a játry dřív, než se dostane do oběhu. Proto se stejný lék podává ústy v mnohem vyšší dávce než do žíly."),
   ("Jazyk", "Sublingválně a bukálně se látka vstřebá rovnou do systémového oběhu — obchází first-pass; proto nitroglycerin pod jazyk."),
   ("Stříkačka", "I.v. má z definice biologickou dostupnost 100 % a okamžitý účinek — ale podané se nedá vzít zpět. I.m. rychlé, s.c. pomalejší (inzulin, hepariny)."),
   ("Náplast", "Nejpomalejší nástup, ale stálá hladina po dny; po sejmutí účinek doznívá z kožního depa.")],
  "„Místní“ podání neznamená „bez celkového účinku“ — oční, nosní i inhalační formy se vstřebávají. Timolol z očních kapek vyvolá bradykardii a bronchospasmus.")

S("O6", "Lékové formy — perorální a orální",
  "PER os = skrz ústa dál do střeva. ORÁLNÍ = zůstává v ústech. A obojí, co má obal nebo je retardované, se NESMÍ DRTIT.",
  [("💊", "Perorální: polkne se, působí po vstřebání"),
   ("🍬", "Orální: pastilka zůstává v ústech"),
   ("🛡️", "Enterosolventní obal projde žaludkem"),
   ("⛔", "Retardované formy NEDRTIT")],
  [("Skrz ústa dál", "Perorální formy: tablety, potahované tablety, tobolky, granuláty, sirupy, suspenze, kapky."),
   ("Zůstává v ústech", "Orální formy: pastilky, žvýkací tablety, ústní vody, gely. Sublingválně a bukálně se látka vstřebá do krve a obejde first-pass."),
   ("Štít", "Enterosolventní obal se rozpadne až ve střevě — chrání látku před kyselinou, nebo žaludek před látkou."),
   ("Zákaz drcení", "Retardované formy (SR, ZOK) uvolňují látku postupně; rozdrcením se uvolní celá denní dávka najednou nebo se látka zničí."),
   ("Pomocné látky", "Nejsou neutrální: laktóza vadí při intoleranci, barviva mohou vyvolat alergii, cukr v sirupech je při dlouhodobé léčbě rizikový.")],
  "Rozpad a rozpuštění předchází vstřebání — u málo rozpustných léčiv je rychlost rozpouštění krokem, který určuje rychlost nástupu účinku.")

S("O7", "Lékové formy — parenterální a dermatologika",
  "Parenterální forma obchází všechny přirozené bariéry — proto musí být sterilní. A co je jednou v žíle, nevrátíš.",
  [("🧼", "Sterilní, apyrogenní, izotonický, izohydrický"),
   ("🩸", "Rychlost sleduje PROKRVENÍ"),
   ("🚫", "Suspenze NIKDY i.v. — embolizace"),
   ("🧴", "Mast → krém → gel: čím tučnější, tím hlouběji")],
  [("Mýdlo", "Přípravek obchází kůži i sliznici, proto musí být sterilní, apyrogenní (bez pyrogenů), izotonický, izohydrický a bez mechanických nečistot."),
   ("Krev", "I.v. okamžitě a se 100% dostupností · i.m. rychle · s.c. pomaleji · depotní formy a náplasti nejpomaleji, ale působí dny až měsíce."),
   ("Zákaz", "Suspenze a emulze se nepodávají i.v. — hrozí embolizace."),
   ("Tuba", "Mast (tučný základ, největší průnik, na suchou kůži) · krém (voda i tuk) · gel (vodný, chladí) · pasta · zásyp · roztok · náplast. Průnik zvyšuje okluze."),
   ("Výhody a nevýhody", "Jistá dostupnost, přesné dávkování, použitelné u zvracení a bezvědomí — proti tomu bolestivost, riziko infekce a embolie, nutný personál a nevratnost podání.")],
  "Lokální kortikoidy dlouhodobě způsobí atrofii kůže a strie — na obličej a do záhybů patří jen slabé přípravky a krátce, protože se tam vstřebávají nejvíc.")

S("O8", "Lékové formy — oční, ušní, nosní, rektalia, vaginalia, inhalanda",
  "„Místní“ znamená KAM to dáváš, ne KDE to působí. Kapka do oka umí zpomalit srdce.",
  [("👁️", "Oční: sterilní, izotonické — timolol dělá bradykardii"),
   ("👃", "Nosní: dekongescencia jen 5–7 dní"),
   ("🫁", "Inhalanda: rozhoduje TECHNIKA, nástavec"),
   ("🍑", "Rektalia: first-pass obchází jen zčásti")],
  [("Oko", "Kapky, masti a gely musí být sterilní a izotonické. Timolol z kapek vyvolá bradykardii a bronchospasmus; vstřebání sníží stisknutí vnitřního koutku po nakapání."),
   ("Nos", "Xylometazolin jen 5–7 dní, jinak vzniká rhinitis medicamentosa. Nosní cestou se podává i desmopresin a sumatriptan k celkovému účinku."),
   ("Plíce", "Aerosolový dávkovač, práškový inhalátor, nebulizace. Nástavec zlepší depozici a sníží nežádoucí účinky — bez něj inhalační kortikoid vyvolá orofaryngeální kandidózu a chrapot."),
   ("Konečník", "Rektalia obcházejí játra jen z dolní části konečníku, vstřebávání je kolísavé; hodí se u zvracení, u dětí a v bezvědomí (diazepam u křečí)."),
   ("Ucho a pochva", "Ušní kapky se nesmí podat při perforaci bubínku. Vaginalia slouží hlavně k místní léčbě, ale i odsud se látka částečně vstřebává.")],
  "Vstřebání ze sliznice může být rychlejší než ze střeva — nosní a bukální sliznice jsou dobře prokrvené a first-pass obcházejí.")

S("O9", "Komunikace, adherence, compliance, placebo a nocebo",
  "Tvoje slova jsou účinná látka. Mají dávku, nástup i nežádoucí účinky — a špatně podaná informace udělá z léku nefunkční lék.",
  [("👂", "COMPLIANCE: pacient dodržuje pokyny"),
   ("🤝", "ADHERENCE: dodrží plán, na kterém se podílel"),
   ("✨", "PLACEBO: očekávání zlepšení — má neurobiologický podklad"),
   ("🌩️", "NOCEBO: očekávání škody vytvoří potíž")],
  [("Ucho", "Compliance — míra, do jaké pacient dodržuje pokyny; pasivní pojetí."),
   ("Podání ruky", "Adherence — pacient se na plánu podílel; konkordance je společné rozhodnutí lékaře a pacienta. Dnes se preferuje adherence, protože zdůrazňuje spoluodpovědnost."),
   ("Jiskra", "Placebo — očekávané zlepšení; má neurobiologický podklad (endogenní opioidy, dopamin), není „vymyšlené“ a zesiluje účinek každého skutečného léku."),
   ("Blesk", "Nocebo — očekávaná škoda; nepříznivé věty a příbalový leták vyvolají potíž. Odsud časté vysazení statinů a antidepresiv."),
   ("Proč léčba selhává", "Nejčastěji ne špatný lék, ale nebraný lék: hypertenze, osteoporóza, složitý režim, mnoho tablet, nežádoucí účinky a obavy z nich, cena, nepochopení a nedůvěra.")],
  "Zlepší to fixní kombinace (méně tablet), dávkování 1× denně, srozumitelné vysvětlení a kontrola. Formulace lékaře je proto sama o sobě účinná látka s vlastní dávkou.")

S("O10", "Přechod látek biologickými membránami",
  "Membrána je TUKOVÁ STĚNA. Projde jen látka lipofilní a NENABITÁ. Nabitá forma zůstane stát přede dveřmi.",
  [("🧈", "Membrána = tuková dvojvrstva"),
   ("🚶", "Prostá difuze: po spádu, zdarma"),
   ("🔋", "Aktivní transport: proti spádu, za ATP"),
   ("🪤", "IONTOVÁ PAST: nabitá forma se nevrátí")],
  [("Máslo", "Přes membránu projde jen látka lipofilní a nenabitá; nabitá (ionizovaná) forma neprojde."),
   ("Chodec", "Prostá difuze — po koncentračním spádu, bez energie a bez přenašeče; hlavní mechanismus u většiny léčiv."),
   ("Baterie", "Aktivní transport — proti spádu, spotřebuje ATP, saturovatelný (např. P-glykoprotein, který léčiva aktivně vypuzuje z buňky). Facilitovaná difuze jde přenašečem, ale po spádu a bez energie."),
   ("Past", "Látka projde membránou v nenabité formě, na druhé straně se při jiném pH nabije a zpět už neprojde — tak se hromadí (a proto se alkalizací moči urychlí vyloučení salicylátů)."),
   ("Bariéry", "Hematoencefalická (těsné spoje + P-glykoprotein), placentární (propustnější, než se čeká), krev–varle, krev–sítnice. Zánět bariéru zpropustní — proto penicilin proniká do CNS jen při meningitidě.")],
  "Proto lokální anestetikum nezabírá v kyselém zánětlivém prostředí: převáží nabitá forma, která přes membránu neprojde k sodíkovému kanálu.")

S("O11", "Základní farmakokinetické parametry a procesy",
  "ADME. A eliminace není totéž co exkrece — eliminace = metabolismus PLUS vylučování.",
  [("🅰️", "A — absorpce (vstup do krve)"),
   ("🅳", "D — distribuce (rozvod do tkání)"),
   ("🅼", "M — metabolismus (přeměna, hlavně játra)"),
   ("🅴", "E — exkrece (vyloučení, hlavně ledviny)")],
  [("ADME", "Čtyři děje osudu léčiva v těle; probíhají současně, ne po sobě."),
   ("Eliminace", "Metabolismus + exkrece dohromady — proto se „eliminace“ a „vylučování“ nesmí zaměňovat."),
   ("F", "Biologická dostupnost — podíl dávky, který se dostane nezměněný do systémového oběhu; i.v. = 100 %."),
   ("Vd", "Distribuční objem — zdánlivý, poměr dávky k plazmatické koncentraci. Vysoké Vd znamená, že látka sedí ve tkáních, ne v krvi (proto ji dialýza neodstraní)."),
   ("CL a t½", "Clearance — objem krve očištěný za čas. Biologický poločas — doba poklesu koncentrace na polovinu; ustálený stav nastane za 4–5 poločasů a stejně dlouho trvá vymizení.")],
  "Farmakokinetika = co tělo dělá s lékem. Farmakodynamika = co lék dělá s tělem. AUC (plocha pod křivkou) je celková expozice, Cmax vrchol a tmax doba do vrcholu.")

S("O12", "Procesy nultého a prvního řádu, saturační kinetika",
  "První řád = ubývá stále stejný PODÍL. Nultý řád = ubývá stále stejné MNOŽSTVÍ. Nasycený enzym víc nestihne, i kdyby chtěl.",
  [("📉", "1. řád: konstantní PODÍL za čas — exponenciála"),
   ("⏳", "0. řád: konstantní MNOŽSTVÍ za čas — přímka"),
   ("🍺", "Ethanol: 0,1–0,15 ‰ za hodinu, vždy stejně"),
   ("⚠️", "Saturace: malé zvýšení dávky → prudký vzestup hladiny")],
  [("Klesající křivka", "Kinetika prvního řádu — odbourává se konstantní podíl (polovina za poločas); platí pro naprostou většinu léčiv, protože enzymy mají kapacitní rezervu."),
   ("Přesýpací hodiny", "Kinetika nultého řádu — enzym je nasycený, odbourává konstantní množství za čas bez ohledu na koncentraci. Pokles je lineární a poločas ztrácí smysl."),
   ("Pivo", "Ethanol se odbourává řádově 0,1–0,15 ‰ za hodinu — rychlost nelze urychlit ničím. Proto nelze počítat „za dva poločasy bude polovina“."),
   ("Michaelisova–Mentenové kinetika", "Přechod mezi obojím: při nízké koncentraci první řád, po nasycení enzymu nultý. Chová se tak fenytoin, salicyláty a theofylin."),
   ("Klinický důsledek", "U saturačního léčiva stačí malé zvýšení dávky a hladina vyskočí do toxického pásma — nystagmus, ataxie, zmatenost u fenytoinu. Proto se měří hladiny.")],
  "Ustálený stav (steady state) nastane za 4–5 poločasů a stejně dlouho trvá, než lék vymizí — proto se u dlouhého poločasu podává nasycovací dávka.")

S("O13", "Absorpce, Batemanova funkce, biologická dostupnost, AUC",
  "Cmax není konec vstřebávání — je to REMÍZA: okamžik, kdy se rychlost vstřebávání vyrovná rychlosti eliminace.",
  [("⚖️", "Cmax = rychlost vstupu se rovná rychlosti eliminace"),
   ("📈", "Batemanova křivka: vzestup, vrchol, pokles"),
   ("🧮", "AUC = celková expozice organismu"),
   ("🔀", "F = podíl dávky, který dorazil nezměněný")],
  [("Váhy", "Ve vrcholu (Cmax) se vstřebávání a eliminace vyrovnají — vstřebávání pokračuje i po něm, jen ho eliminace převáží."),
   ("Křivka", "Batemanova funkce popisuje průběh koncentrace po jednorázovém perorálním podání: vzestupná fáze (převažuje absorpce), vrchol, sestupná fáze (převažuje eliminace)."),
   ("Kalkulačka", "AUC = plocha pod křivkou = celková expozice; podle ní se srovnává originál s generikem (bioekvivalence)."),
   ("Biologická dostupnost", "F = podíl podané dávky, který se dostane nezměněný do systémového oběhu. Snižuje ji neúplné vstřebání a first-pass metabolismus."),
   ("Co ovlivní vstřebání", "Léková forma, rozpustnost, pH, jídlo, motilita, prokrvení, současně podaná léčiva (antacida, železo, vápník váží tetracykliny a chinolony).")],
  "tmax vypovídá o rychlosti vstřebávání, Cmax a AUC o rozsahu. Generikum musí mít shodné AUC i Cmax v předepsaném rozmezí — proto se u něj nezkoumá znovu účinnost.")

S("O14", "Distribuce, distribuční objem, redistribuce, vazba na bílkoviny, bariéry",
  "Vd je ZDÁNLIVÝ objem — ne skutečný. Vysoké Vd znamená: „lék není v krvi, sedí ve tkáních“ — a dialýza ho nedostane ven.",
  [("🫙", "Vd = dávka ÷ plazmatická koncentrace"),
   ("🛋️", "Vysoké Vd → lék je ve tkáních, ne v krvi"),
   ("🔗", "Vázaná frakce je NEÚČINNÁ, jen volná působí"),
   ("🧠", "Bariéry: hematoencefalická, placentární")],
  [("Nádoba", "Distribuční objem je zdánlivý — je to počítaná veličina, ne anatomický prostor. Může mnohonásobně převýšit objem těla."),
   ("Gauč", "Vysoké Vd = lék je uložený ve tkáních (tuk, sval), v krvi ho je málo — proto ho hemodialýza neodstraní (digoxin, antidepresiva)."),
   ("Řetěz", "Účinná je jen volná frakce. Albumin váže kyselé látky (warfarin, fenytoin), orosomukoid (kyselý α1-glykoprotein) zásadité. Při hypoalbuminemii stoupá volná frakce a s ní účinek i toxicita."),
   ("Mozek", "Hematoencefalická bariéra — těsné spoje a P-glykoprotein; propustí jen lipofilní a nenabité látky. Placentární bariéra je propustnější, než se obvykle čeká."),
   ("Redistribuce", "Thiopental uspí rychle, protože se dostane do mozku, a probudí rychle, protože se přesune do svalu a tuku — konec účinku dělá přesun, ne eliminace.")],
  "Vytěsnění z vazby na bílkovinu je klasická interakce (sulfonamidy vytěsní warfarin), ale samo o sobě bývá klinicky přechodné — nebezpečné je, když se k němu přidá i útlum metabolismu.")

S("O15", "Eliminace, poločas, fáze α a β, eliminační konstanta, clearance",
  "Za 4–5 poločasů se hladina ustálí — a stejně dlouho trvá, než lék po vysazení zmizí. Poločas je hodiny, ne účinek.",
  [("½", "t½ — pokles koncentrace na polovinu"),
   ("🅰️", "Fáze α = distribuce · fáze β = vlastní eliminace"),
   ("🚰", "CL — objem krve očištěný za jednotku času"),
   ("4️⃣", "4–5 poločasů: ustálený stav i vymizení")],
  [("Polovina", "Biologický poločas — doba, za kterou klesne koncentrace na polovinu. U kinetiky prvního řádu je konstantní a nezávisí na dávce."),
   ("Dvě fáze", "Po i.v. podání klesá koncentrace nejprve strmě (fáze α — rozvod do tkání), pak pozvolna (fáze β — skutečná eliminace). Poločas se počítá z fáze β."),
   ("Kohoutek", "Clearance = objem plazmy zcela očištěný za jednotku času; sčítá se renální a jaterní (CL = CLren + CLhep). Vztah: t½ = 0,693 × Vd ÷ CL."),
   ("Čtyřka", "Za 4–5 poločasů se dosáhne ustáleného stavu při opakovaném podávání — a stejně dlouho trvá vymizení po vysazení."),
   ("Eliminační konstanta", "kel — podíl látky odstraněný za jednotku času; t½ = 0,693 ÷ kel.")],
  "Poločas roste, když klesne clearance (jaterní nebo renální selhání) NEBO když stoupne Vd — proto nestačí sledovat jen ledviny.")

S("O16", "Dávkovací režim, kumulace, kumulační index",
  "Když podáš další dávku dřív, než se vyloučí ta předchozí, lék se HROMADÍ. Nasycovací dávka řeší čekání, udržovací drží hladinu.",
  [("📚", "KUMULACE: interval kratší než eliminace"),
   ("🚀", "NASYCOVACÍ dávka — zkrátí čekání na účinek"),
   ("🔄", "UDRŽOVACÍ dávka — nahrazuje ztrátu"),
   ("📊", "Kratší interval = menší kolísání hladiny")],
  [("Hromada", "Kumulace nastane, je-li dávkovací interval kratší než doba potřebná k eliminaci; ustálí se po 4–5 poločasech."),
   ("Raketa", "Nasycovací dávka = Vd × cílová koncentrace. Podává se, když je poločas dlouhý a nelze čekat 4–5 poločasů na účinek."),
   ("Kolotoč", "Udržovací dávka = CL × cílová koncentrace × interval. Nahrazuje to, co se za interval vyloučí."),
   ("Graf", "Krátký interval a malé dávky = plochá, stabilní hladina. Dlouhý interval a velké dávky = větší kolísání mezi vrcholem a údolím — riziko u léčiv s úzkým terapeutickým oknem."),
   ("Kumulační index", "Poměr koncentrace v ustáleném stavu k té po první dávce; udává, kolikrát se hladina nahromadí.")],
  "Nasycovací dávka závisí na Vd, udržovací na clearance — proto se u renální insuficience krátí udržovací dávka, ale nasycovací zůstává stejná.")

S("O17", "Biotransformace léčiv, fáze, příklady",
  "Fáze I. látku ROZBIJE a odhalí funkční skupinu. Fáze II. na ni PŘILEPÍ velkou vodorozpustnou molekulu, aby šla ven.",
  [("🔨", "I. fáze: oxidace, redukce, hydrolýza (CYP450)"),
   ("🏷️", "II. fáze: konjugace — glukuronidace, sulfatace"),
   ("💧", "Cíl: z lipofilní látky udělat hydrofilní"),
   ("⚡", "Metabolit může být ÚČINNĚJŠÍ než původní látka")],
  [("Kladivo", "I. fáze — oxidace (hlavně cytochromy P450, nejvíc CYP3A4), redukce, hydrolýza. Vzniká reaktivnější metabolit s odhalenou funkční skupinou."),
   ("Štítek", "II. fáze — konjugace: glukuronidace, sulfatace, acetylace, methylace, vazba na glutathion. Produkt je velký, polární a snadno vyloučitelný."),
   ("Kapka", "Smyslem je změnit lipofilní látku na hydrofilní — jinak by se v ledvinách stále zpětně vstřebávala."),
   ("Blesk", "Proléčivo se aktivuje až metabolismem: kodein → morfin (CYP2D6), enalapril → enalaprilát, cyklofosfamid, klopidogrel. Metabolit může být i toxický: paracetamol → NAPQI."),
   ("Kde", "Především játra, ale i střevní stěna, plíce, ledviny a plazma (esterázy).")],
  "Novorozenec má nezralou glukuronidaci — odtud gray baby syndrom po chloramfenikolu. U starších klesá hlavně I. fáze, II. fáze zůstává poměrně zachovaná.")

S("O18", "Úloha jater v eliminaci léčiv, first-pass efekt",
  "Co se vstřebá ze střeva, jde NEJPRVE do jater — teprve zbytek doputuje do těla. Proto je perorální dávka mnohonásobně vyšší než nitrožilní.",
  [("🚪", "Střevo → portální žíla → JÁTRA → oběh"),
   ("📉", "First-pass sníží dostupnost, někdy pod 10 %"),
   ("🔁", "Enterohepatální oběh: žluč → střevo → zpět"),
   ("🫀", "Vysoká extrakce = závisí na PRŮTOKU játry")],
  [("Vrátnice", "Vše vstřebané ze střeva projde portální žílou játry dřív, než se dostane do systémového oběhu."),
   ("Pokles", "Silný first-pass mají nitroglycerin, propranolol, morfin, verapamil, lidokain — proto se nitroglycerin podává sublingválně a lidokain se ústy nepodává vůbec."),
   ("Kruh", "Enterohepatální oběh: látka se vyloučí žlučí, ve střevě se uvolní zpět a znovu vstřebá — prodlužuje účinek (kontraceptiva; proto antibiotika mohou jejich účinnost snížit)."),
   ("Srdce", "U léčiv s vysokou jaterní extrakcí limituje eliminaci průtok játry — při srdečním selhání a šoku hladiny stoupají. U nízké extrakce rozhoduje enzymatická kapacita a vazba na bílkoviny."),
   ("Jaterní selhání", "Klesá metabolismus i tvorba albuminu, roste volná frakce a zkratový oběh obchází játra — dávky se snižují.")],
  "Rektální podání obchází first-pass jen zčásti (dolní část konečníku), proto je vstřebávání kolísavé. Sublingválně a transdermálně se játra obejdou zcela.")

S("O19", "Inhibice a indukce enzymů léčivy, klinický význam",
  "INHIBICE je rychlá a hladina VYSKOČÍ. INDUKCE je pomalá a hladina SPADNE — musí se nasyntetizovat nový enzym.",
  [("🛑", "INHIBICE: během hodin ↑ hladina → toxicita"),
   ("🏭", "INDUKCE: za dny až týdny ↓ hladina → selhání léčby"),
   ("🍊", "Grapefruit, azoly, makrolidy = inhibitory"),
   ("🔥", "Rifampicin, karbamazepin, fenytoin, třezalka = induktory")],
  [("Stopka", "Inhibitor obsadí enzym hned — hladina druhého léčiva stoupá během hodin až dnů a hrozí toxicita."),
   ("Továrna", "Induktor spouští tvorbu nového enzymu — trvá dny až týdny, než se plně projeví, a stejně dlouho odeznívá. Hladina druhého léčiva klesne a léčba selže."),
   ("Inhibitory", "Grapefruitová šťáva, azolová antimykotika (flukonazol, itrakonazol), makrolidy (erythromycin, klarithromycin — nikoli azithromycin), ciprofloxacin, verapamil, amiodaron, ritonavir."),
   ("Induktory", "Rifampicin, karbamazepin, fenytoin, fenobarbital, třezalka tečkovaná; chronicky alkohol a kouření (CYP1A2)."),
   ("Co to udělá", "Rifampicin sníží účinnost hormonální kontracepce, warfarinu a antiretrovirotik. Klarithromycin se statinem zvýší riziko rabdomyolýzy.")],
  "U proléčiva je to obráceně: inhibitor CYP2D6 (fluoxetin, paroxetin) sníží účinek kodeinu a klopidogrelu, protože zabrání jejich AKTIVACI.")

S("O20", "Vylučování léčiv renální a extrarenální",
  "Ledvina dělá tři věci: FILTRUJE, SEKRETUJE a část zase VSTŘEBÁ ZPĚT. Vyloučí se jen to, co je vodorozpustné.",
  [("🫧", "Glomerulární filtrace: jen VOLNÁ frakce"),
   ("➡️", "Tubulární sekrece: aktivní, saturovatelná"),
   ("↩️", "Zpětná resorpce: lipofilní látky se vracejí"),
   ("💨", "Extrarenálně: žluč, plíce, mléko, sliny, pot")],
  [("Filtr", "Glomerulem projde jen volná (nenavázaná) frakce; látka vázaná na albumin se nefiltruje."),
   ("Šipka ven", "Tubulární sekrece je aktivní transport se společnými přenašeči — proto probenecid zpomaluje vylučování penicilinu (soupeří o týž přenašeč)."),
   ("Šipka zpět", "Lipofilní a nenabité látky se z tubulu vstřebávají zpět. Změnou pH moči se to dá ovlivnit: alkalizace bikarbonátem urychlí vyloučení kyselých látek (salicyláty, barbituráty)."),
   ("Pára", "Extrarenální cesty: žluč a stolice (a enterohepatální oběh), plíce (inhalační anestetika, ethanol — odtud dechová zkouška), mateřské mléko, sliny, pot."),
   ("Renální insuficience", "Dávky léčiv vylučovaných ledvinami se snižují podle clearance kreatininu — aminoglykosidy, digoxin, metformin, lithium, mnohá antibiotika.")],
  "Vyloučit se dá jen látka vodorozpustná — proto předchází biotransformace. Lipofilní látka by se v tubulu jen stále dokola vstřebávala zpět.")

S("O21", "Účinek léčiv obecně, způsob účinku na molekulární úrovni",
  "Většina léčiv se váže na CÍLOVOU STRUKTURU — receptor, enzym, kanál nebo přenašeč. Nespecifický účinek žádnou cílovou strukturu nepotřebuje.",
  [("🎯", "SPECIFICKÝ: vazba na cílovou strukturu"),
   ("🧂", "NESPECIFICKÝ: fyzikálně-chemický (antacida, osmotika)"),
   ("🔓", "AGONISTA aktivuje · ANTAGONISTA blokuje"),
   ("⚗️", "Enzymy, kanály, přenašeče, nukleové kyseliny")],
  [("Terč", "Specifický účinek — vazba na receptor, enzym, iontový kanál, přenašeč nebo nukleovou kyselinu; je strukturně závislý a nasytitelný."),
   ("Sůl", "Nespecifický účinek — fyzikálně-chemický, bez cílové struktury: antacida neutralizují kyselinu, osmotická projímadla táhnou vodu, aktivní uhlí adsorbuje, celková anestetika mění vlastnosti membrány."),
   ("Klíč", "Agonista se váže a receptor aktivuje (má afinitu i vnitřní aktivitu). Antagonista se váže, ale neaktivuje (má jen afinitu) — brání navázání agonisty."),
   ("Cílové struktury", "Enzymy (statiny na HMG-CoA-reduktázu, ACE inhibitory), iontové kanály (lokální anestetika na sodíkové, blokátory kalciových kanálů), přenašeče (SSRI na serotoninový transportér, IPP na H+/K+-ATPázu), nukleové kyseliny (cytostatika, chinolony).")],
  "Účinek léčiva je vždy jen zesílení nebo zeslabení děje, který v těle už existuje — lék nevytváří novou funkci.")

S("O22", "Specifický účinek, cílové struktury, receptorová teorie, typy receptorů",
  "AFINITA = jak pevně se to naváže. VNITŘNÍ AKTIVITA = jestli to po navázání něco udělá. Antagonista má afinitu, ale nulovou aktivitu.",
  [("🧲", "AFINITA: síla vazby"),
   ("⚡", "VNITŘNÍ AKTIVITA: co to po navázání spustí"),
   ("🚪", "Ionotropní (ms) · metabotropní G-protein (s)"),
   ("🧬", "Nitrobuněčné receptory: hodiny až dny")],
  [("Magnet", "Afinita — jak pevně se ligand váže; určuje potřebnou koncentraci."),
   ("Blesk", "Vnitřní aktivita — co se po navázání stane. Plný agonista 1, parciální agonista mezi 0 a 1 (buprenorfin), antagonista 0, inverzní agonista pod 0 (utlumí i bazální aktivitu — H1-antihistaminika)."),
   ("Dveře", "Ionotropní receptory jsou samy iontovým kanálem — účinek za milisekundy (nikotinový acetylcholinový, GABA-A, NMDA). Metabotropní jdou přes G-protein a druhého posla — sekundy (muskarinové, adrenergní, opioidní)."),
   ("DNA", "Nitrobuněčné (jaderné) receptory mění přepis genů — účinek za hodiny až dny (kortikosteroidy, hormony štítné žlázy, pohlavní hormony). Odsud jejich pomalý nástup."),
   ("Antagonismus", "Kompetitivní — překonatelný vyšší dávkou agonisty, posouvá křivku doprava. Nekompetitivní — nepřekonatelný, snižuje maximum.")],
  "Down-regulace (úbytek receptorů při trvalé stimulaci) vysvětluje toleranci; up-regulace při dlouhé blokádě vysvětluje rebound fenomén po náhlém vysazení β-blokátoru.")

S("O23", "Dávka a účinek, terapeutický index, terapeutické okno, riziko, NNT",
  "Terapeutické okno je pruh mezi „ještě to nefunguje“ a „už to škodí“. U digoxinu, warfarinu a lithia je ten pruh úzký jako vlas.",
  [("🪟", "TERAPEUTICKÉ OKNO: účinné, ale ne toxické"),
   ("📏", "TI = TD50 ÷ ED50 — čím vyšší, tím bezpečnější"),
   ("🩺", "Úzké okno → MONITOROVAT HLADINY"),
   ("🔢", "NNT: kolik pacientů léčit, aby prospěl jednomu")],
  [("Okno", "Terapeutické okno — rozmezí koncentrací mezi minimální účinnou a toxickou."),
   ("Pravítko", "Terapeutický index TI = TD50 ÷ ED50 (u zvířat LD50 ÷ ED50). ED50 = dávka účinná u poloviny, TD50 = toxická u poloviny, LD50 = smrtelná pro polovinu."),
   ("Fonendoskop", "Úzký terapeutický index mají digoxin, warfarin, theofylin, lithium, fenytoin, aminoglykosidy, cyklosporin — u nich se měří plazmatické hladiny."),
   ("Číslice", "NNT (number needed to treat) — kolik pacientů je třeba léčit, aby se u jednoho zabránilo příhodě; nízké NNT = účinná léčba. Obdobně NNH pro poškození."),
   ("Křivka", "Vztah dávky a účinku je sigmoidní (v logaritmickém měřítku). Účinnost (efficacy) = jak vysokého maxima lék dosáhne; potence = jak malá dávka k tomu stačí.")],
  "Potentnější lék není lepší lék — znamená jen nižší potřebnou dávku. Rozhoduje maximální dosažitelný účinek a bezpečnost, ne velikost tablety.")

S("O24", "Vlivy působící na kinetiku a dynamiku léčiv",
  "Stejná dávka, jiný člověk, jiný účinek. Rozhodují játra, ledviny, věk, geny, další léky a jídlo.",
  [("👶", "VĚK: novorozenec i senior mají jinou kinetiku"),
   ("🫘", "ORGÁNY: játra a ledviny určují eliminaci"),
   ("🧬", "GENY: rychlý a pomalý metabolizátor"),
   ("🍽️", "JÍDLO, kouření, alkohol, další léky")],
  [("Dítě", "Novorozenec má nezralou glukuronidaci a vyšší podíl vody; senior má nižší glomerulární filtraci, nižší albumin, méně svaloviny a více tuku (lipofilní léčiva se hromadí)."),
   ("Ledvina", "Jaterní selhání snižuje metabolismus a tvorbu albuminu; renální insuficience zpomaluje vylučování. U obojího se dávky snižují."),
   ("DNA", "Polymorfismus CYP2D6, CYP2C9, CYP2C19, NAT2, TPMT rozhoduje, zda je člověk pomalý, či ultrarychlý metabolizátor."),
   ("Talíř", "Jídlo mění vstřebávání (mléko a antacida váží tetracykliny), grapefruit inhibuje CYP3A4, kouření indukuje CYP1A2 (theofylin, klozapin, olanzapin), alkohol akutně inhibuje a chronicky indukuje."),
   ("Dynamika", "Mění se i citlivost cílové struktury: u seniorů vyšší citlivost na benzodiazepiny a opioidy, při hypokalemii vyšší toxicita digoxinu.")],
  "Gravidita mění obojí: roste objem distribuce a glomerulární filtrace, klesá albumin — a přibývá otázka, co projde placentou.")

S("O25", "Lékové interakce",
  "Interakce jsou dvojího druhu: FARMAKOKINETICKÉ (lék A změní hladinu léku B) a FARMAKODYNAMICKÉ (oba táhnou za týž provaz).",
  [("🧪", "KINETICKÉ: vstřebávání, vazba, metabolismus, vylučování"),
   ("🤼", "DYNAMICKÉ: sčítání nebo rušení účinku"),
   ("🍇", "Grapefruit inhibuje CYP3A4"),
   ("🌼", "Třezalka indukuje CYP3A4 a P-glykoprotein")],
  [("Zkumavka", "Farmakokinetické: vstřebávání (antacida a železo váží tetracykliny a chinolony), vazba na bílkoviny (vytěsnění warfarinu), metabolismus (inhibice a indukce CYP450), vylučování (probenecid a penicilin)."),
   ("Přetahovaná", "Farmakodynamické: synergie (alkohol + benzodiazepiny = útlum dechu; ACE inhibitor + kalium šetřící diuretikum = hyperkalemie) nebo antagonismus (β-blokátor ruší účinek β2-agonisty u astmatu)."),
   ("Grapefruit", "Inhibuje střevní CYP3A4 → prudce zvýší hladinu statinů, blokátorů kalciových kanálů a imunosupresiv."),
   ("Třezalka", "Silný induktor CYP3A4 a P-glykoproteinu → sníží účinnost kontracepce, warfarinu, cyklosporinu, digoxinu a antiretrovirotik."),
   ("Nejrizikovější dvojice", "Warfarin s čímkoli · statin s makrolidem nebo azolem · NSA s antikoagulanciem · látky prodlužující QT navzájem · serotonergní léčiva navzájem.")],
  "Nejvíc interakcí nevzniká z léků na předpis, ale z toho, co pacient nehlásí: volně prodejná NSA, doplňky stravy a bylinky.")

S("O26", "Farmakogenetika, genetický polymorfismus",
  "Stejná dávka může být u jednoho neúčinná a u druhého toxická — rozhoduje, jestli je POMALÝ, nebo ULTRARYCHLÝ metabolizátor.",
  [("🐢", "POMALÝ metabolizátor: hladina stoupá → toxicita"),
   ("🐇", "ULTRARYCHLÝ: hladina klesá → léčba nefunguje"),
   ("💊", "U PROLÉČIVA je to naopak"),
   ("🧾", "Testuje se: HLA-B*5701, TPMT, G6PD")],
  [("Želva", "Pomalý metabolizátor odbourává léčivo pomalu — hladina stoupá a hrozí toxicita (CYP2D6 a antidepresiva, CYP2C9 a warfarin)."),
   ("Zajíc", "Ultrarychlý metabolizátor odbourá léčivo dřív, než stačí zabrat — léčba selhává."),
   ("Proléčivo", "U proléčiva se to obrací: ultrarychlý metabolizátor CYP2D6 vytvoří z kodeinu nebezpečně mnoho morfinu, pomalý metabolizátor nemá z kodeinu ani z klopidogrelu žádný účinek."),
   ("Testy", "HLA-B*5701 před abakavirem (hypersenzitivita), HLA-B*5801 před allopurinolem, TPMT před azathioprinem a 6-merkaptopurinem (myelosuprese), G6PD před primachinem a sulfonamidy (hemolýza), NAT2 a rychlost acetylace izoniazidu.")],
  "Farmakogenetika vysvětluje i idiosynkrazii — geneticky podmíněnou neobvyklou reakci, například maligní hypertermii po sukcinylcholinu a halotanu.")

S("O27", "Tolerance, tachyfylaxe, rezistence",
  "TOLERANCE se buduje dny až týdny. TACHYFYLAXE je bleskurychlá — přijde během minut a novou dávkou ji nepřekonáš.",
  [("📉", "TOLERANCE: postupně slábne účinek"),
   ("⚡", "TACHYFYLAXE: rychlé vyčerpání, během minut"),
   ("🦠", "REZISTENCE: netýká se člověka, ale mikroba"),
   ("🔀", "ZKŘÍŽENÁ tolerance mezi látkami stejného mechanismu")],
  [("Klesající křivka", "Tolerance — na týž účinek je třeba stále vyšší dávka. Farmakodynamická (down-regulace receptorů) nebo farmakokinetická (indukce vlastního metabolismu, např. barbituráty)."),
   ("Blesk", "Tachyfylaxe — velmi rychlý pokles účinku při opakovaném podání v krátkém sledu, typicky vyčerpáním zásoby mediátoru (efedrin) nebo obsazením receptorů; zvýšení dávky nepomůže. Vzniká i u nitrátů, proto se ponechává noční interval bez náplasti."),
   ("Bakterie", "Rezistence je vlastnost mikroorganismu, ne pacienta — primární (přirozená) nebo získaná (mutace, přenos plazmidu). Nepleť si ji s tolerancí."),
   ("Křížení", "Zkřížená tolerance existuje mezi látkami se stejným mechanismem — alkohol, benzodiazepiny a barbituráty; morfin a ostatní opioidy.")],
  "Tolerance na různé účinky téže látky se vyvíjí různě rychle: u opioidů rychle na euforii a útlum dechu, ale prakticky vůbec na zácpu a miózu.")

S("O28", "Vliv průvodních onemocnění, polypragmazie",
  "Každý další lék zvyšuje riziko interakce geometricky. A předepsat lék na nežádoucí účinek jiného léku je začátek KASKÁDY.",
  [("🫘", "Ledviny a játra: snížit dávku"),
   ("🫀", "Srdeční selhání: méně průtoku, hůř se eliminuje"),
   ("♾️", "Preskripční KASKÁDA: lék na nežádoucí účinek léku"),
   ("🧹", "DEPRESKRIPCE: pravidelná revize medikace")],
  [("Ledvina", "Renální insuficience — snížit dávku léčiv vylučovaných ledvinami (aminoglykosidy, digoxin, metformin, lithium). Jaterní selhání — nižší metabolismus, nižší albumin, zkratový oběh."),
   ("Srdce", "Srdeční selhání snižuje průtok játry i ledvinami; u léčiv s vysokou jaterní extrakcí hladina stoupá."),
   ("Kaskáda", "Preskripční kaskáda: metoklopramid vyvolá parkinsonské projevy → nasadí se antiparkinsonikum. Blokátor kalciových kanálů vyvolá otoky → nasadí se diuretikum. Vždy se nejdřív ptej, jestli nový příznak není nežádoucí účinek."),
   ("Koště", "Depreskripce — plánované vysazení léků, které už nepřinášejí užitek; u polymorbidních je stejně důležitá jako nasazení."),
   ("Polypragmazie", "Zpravidla 5 a více léčiv současně; roste riziko interakcí, pádů, hospitalizací a klesá adherence.")],
  "Kontraindikace bývají dané právě přidruženou chorobou: β-blokátor u astmatu, NSA u renální insuficience a vředové choroby, metformin při riziku laktátové acidózy.")

S("O29", "Nežádoucí účinky léčiv",
  "Typ A je ZESÍLENÝ ÚČINEK — dá se předvídat, závisí na dávce, je častý. Typ B je BIZARNÍ — nepředvídatelný, na dávce nezávisí, ale zabíjí.",
  [("📈", "TYP A (Augmented): závisí na dávce, předvídatelný"),
   ("🎲", "TYP B (Bizarre): nezávisí na dávce, nepředvídatelný"),
   ("⏱️", "C chronický · D pozdní · E po vysazení"),
   ("📮", "HLÁŠENÍ SÚKL — farmakovigilance")],
  [("Vzestup", "Typ A — vyplývá z farmakologického účinku, závisí na dávce, je častý a málokdy smrtelný; řeší se snížením dávky. Krvácení po warfarinu, hypoglykemie po inzulinu, bradykardie po β-blokátoru."),
   ("Kostka", "Typ B — nesouvisí s dávkou ani s mechanismem, nedá se předvídat; je vzácný, ale často závažný. Alergie, aplastická anemie po chloramfenikolu, maligní hypertermie, Stevensův–Johnsonův syndrom."),
   ("Hodiny", "Typ C — chronický, při dlouhém podávání (osteoporóza po kortikoidech). Typ D — pozdní (teratogenita, kancerogenita). Typ E — po náhlém vysazení (rebound hypertenze, adrenální insuficience)."),
   ("Schránka", "Podezření na nežádoucí účinek se hlásí SÚKL; u nově registrovaných léčiv (černý trojúhelník) se hlásí i podezření běžná. Právě tak se odhalí to, co ve fázi III nevyšlo najevo.")],
  "Typ A se řeší úpravou dávky. Typ B znamená lék vysadit a už nikdy nepodat — a poznamenat do dokumentace.")

S("O30", "Léková alergie, idiosynkrazie",
  "Alergie POTŘEBUJE PŘEDCHOZÍ SETKÁNÍ — první podání senzibilizuje, druhé spustí reakci. Nesnášenlivost není alergie.",
  [("1️⃣", "1. kontakt: senzibilizace, bez příznaků"),
   ("2️⃣", "2. kontakt: reakce — IgE, do minut"),
   ("💉", "ANAFYLAXE → ADRENALIN i.m., ne antihistaminikum"),
   ("🧬", "IDIOSYNKRAZIE: geneticky podmíněná, ne imunitní")],
  [("První setkání", "Senzibilizace probíhá bez příznaků; proto reakce nikdy nepřijde při úplně prvním podání."),
   ("Druhé setkání", "Typ I (IgE, časný) — kopřivka, angioedém, bronchospasmus, anafylaxe během minut. Typ II cytotoxický, typ III imunokomplexový (sérová nemoc), typ IV pozdní buněčný (kontaktní ekzém, makulopapulózní exantém za dny)."),
   ("Adrenalin", "U anafylaxe je lékem první volby adrenalin intramuskulárně do stehna; antihistaminika a kortikosteroidy jsou pouze doplňkové a působí příliš pomalu."),
   ("Idiosynkrazie", "Geneticky podmíněná neobvyklá reakce bez účasti imunity — hemolýza při deficitu G6PD, maligní hypertermie po sukcinylcholinu, prodloužená apnoe při atypické pseudocholinesteráze."),
   ("Zkřížená alergie", "Mezi peniciliny a cefalosporiny existuje, ale je nižší, než se dřív uvádělo; anafylaxe na penicilin v anamnéze je však kontraindikací celé skupiny.")],
  "Nauzea po antibiotiku není alergie, ale nesnášenlivost — přesto se často zapíše jako alergie a pacient pak zbytečně přijde o celou lékovou skupinu.")

S("O31", "Karcinogenní a mutagenní účinky",
  "Mutagen poškodí DNA. Karcinogen z toho udělá nádor. A projeví se to za roky až desetiletí — proto to žádná studie nezachytí včas.",
  [("🧬", "MUTAGEN: poškození DNA (genové, chromozomové)"),
   ("🦀", "KARCINOGEN: iniciace → promoce → progrese"),
   ("⏳", "Latence roky až desetiletí"),
   ("🧪", "Testy: Amesův test, testy in vitro a na zvířeti")],
  [("DNA", "Mutagenita — poškození genetické informace: genové mutace, chromozomové aberace, změny počtu chromozomů. Postihuje-li zárodečné buňky, přenáší se na potomstvo."),
   ("Nádor", "Karcinogeneze má fáze iniciace (nevratné poškození DNA), promoce (podpora množení poškozeného klonu) a progrese. Genotoxické karcinogeny nemají bezpečnou dávku, negenotoxické (hormonální, imunosupresivní) působí nepřímo."),
   ("Přesýpací hodiny", "Dlouhá latence je důvod, proč se karcinogenita odhalí až po letech užívání — a proč se testuje předklinicky."),
   ("Zkumavka", "Amesův test (mutagenita na bakteriích), testy chromozomových aberací, dlouhodobé studie na hlodavcích."),
   ("Příklady", "Cytostatika (alkylační látky — sekundární leukemie), imunosupresiva (lymfomy a kožní nádory), estrogeny bez gestagenu (karcinom endometria), tabákový kouř.")],
  "Cytostatika léčí nádor a zároveň zvyšují riziko nádoru druhého — to není rozpor, ale poměr rizika a prospěchu, který se u každého pacienta váží zvlášť.")

S("O32", "Léčiva v těhotenství, teratogenní účinek, léčiva v době kojení",
  "Nejzranitelnější je ORGANOGENEZE (3.–8. týden) — a to je doba, kdy žena často ještě neví, že je těhotná.",
  [("🥚", "0.–2. týden: „všechno, nebo nic“"),
   ("⚠️", "3.–8. týden: ORGANOGENEZE — malformace"),
   ("📈", "Od 9. týdne: růst a funkce, ne tvar"),
   ("🍼", "Kojení: podat hned PO kojení, ne před")],
  [("Vajíčko", "Do 2. týdne platí pravidlo „všechno, nebo nic“ — buď zárodek zanikne, nebo se poškození plně opraví."),
   ("Varování", "3.–8. týden je organogeneze a období největšího rizika strukturních vad. Klasické teratogeny: isotretinoin a ostatní retinoidy, thalidomid, warfarin, valproát, karbamazepin, fenytoin, metotrexát, mykofenolát, ACE inhibitory a sartany, tetracykliny, živé vakcíny, inhibitory 5-α-reduktázy."),
   ("Růst", "Po organogenezi vznikají funkční poruchy a poruchy růstu — ACE inhibitory poškozují ledviny plodu, NSA předčasně uzavírají ductus arteriosus, tetracykliny barví zuby."),
   ("Kojení", "Do mléka přechází nejspíš látka lipofilní, málo vázaná na bílkoviny a zásaditá. Podává se ihned po kojení, aby do dalšího přiložení hladina klesla. Kontraindikovány jsou cytostatika, radiofarmaka, lithium, amiodaron."),
   ("Rozhodování", "Neléčená nemoc matky (epilepsie, astma, těžká deprese, infekce) ohrožuje plod často víc než lék — proto se neléčí „nulovým rizikem“, ale poměrem rizika a prospěchu.")],
  "Kyselina listová se podává preventivně už před početím jako prevence rozštěpů neurální trubice — u žen na antiepilepticích ve vyšší dávce.")

S("O33", "Farmakoterapie v dětství",
  "Dítě není zmenšený dospělý. Dávkuje se na KILOGRAM nebo na povrch těla — a některé léky nesmí dostat vůbec.",
  [("⚖️", "Dávka na kg hmotnosti nebo na m² povrchu"),
   ("🍼", "Novorozenec: nezralá glukuronidace, více vody"),
   ("🚫", "Zakázáno: tetracykliny, chinolony, kodein, ASA"),
   ("🧃", "Formy: sirupy, kapky, čípky — ne velké tablety")],
  [("Váhy", "Dávkuje se na kilogram tělesné hmotnosti, u cytostatik na plochu povrchu těla; nikdy se nepřepočítává „zlomkem dávky dospělého“ od oka."),
   ("Kojenec", "Novorozenec má nezralé jaterní enzymy (glukuronidaci — odtud gray baby syndrom po chloramfenikolu), vyšší podíl tělesné vody (vyšší Vd pro hydrofilní léčiva), nižší vazbu na bílkoviny a nezralou glomerulární filtraci."),
   ("Zákaz", "Tetracykliny do 8 let (zbarvení zubů a hypoplazie skloviny) · chinolony (poškození chrupavky) · kodein a tramadol (útlum dechu u ultrarychlých metabolizátorů) · kyselina acetylsalicylová u virózy (Reyeův syndrom) · metoklopramid (dystonie)."),
   ("Sirup", "Perorální roztoky, sirupy, kapky, čípky; při dlouhodobé léčbě pozor na obsah cukru a etanolu v přípravku."),
   ("Off-label", "Řada léčiv nemá u dětí registraci — podávají se off-label na základě odborných doporučení, protože klinické studie na dětech jsou vzácné.")],
  "Paracetamol a ibuprofen jsou základní antipyretika dětského věku; kyselina acetylsalicylová se u dětí s horečnatým virovým onemocněním nepodává pro riziko Reyeova syndromu.")

S("O34", "Farmakoterapie ve stáří, polypragmazie",
  "Ve stáří: „START LOW, GO SLOW“. Klesá filtrace, klesá albumin, přibývá tuku — a citlivost mozku na tlumivé léky roste.",
  [("🐢", "Začni nízkou dávkou, zvyšuj pomalu"),
   ("🫘", "Klesá glomerulární filtrace — i při normálním kreatininu"),
   ("🧠", "Vyšší citlivost na benzodiazepiny a opioidy"),
   ("📋", "Beersova kritéria, STOPP/START — nevhodná léčiva")],
  [("Želva", "Start low, go slow — nižší úvodní dávka a pomalá titrace; kontrola účinku i nežádoucích účinků."),
   ("Ledvina", "Glomerulární filtrace klesá s věkem i při normálním sérovém kreatininu, protože ubývá svalové hmoty — proto se počítá clearance, ne jen kreatinin."),
   ("Mozek", "Roste citlivost na benzodiazepiny, opioidy, anticholinergika a antipsychotika — riziko pádů, zmatenosti a deliria. Ubývá svalu a přibývá tuku, takže lipofilní léčiva se hromadí a mají delší poločas."),
   ("Seznam", "Beersova kritéria a STOPP/START vyjmenovávají léčiva u seniorů nevhodná (dlouhodobě působící benzodiazepiny, anticholinergika, NSA) a naopak ta, která chybějí."),
   ("Anticholinergní zátěž", "Sčítá se z mnoha léků najednou (antihistaminika I. generace, tricyklika, spasmolytika, některá antipsychotika) — výsledkem je zmatenost, retence moči, zácpa a pády.")],
  "Nový příznak u seniora je nežádoucí účinek léku, dokud se neprokáže opak — teprve pak se hledá nová diagnóza. Jinak vzniká preskripční kaskáda.")

S("O35", "Biologická léčba: rozdělení, názvosloví, biosimilars",
  "Konec názvu prozradí, co to je: -MAB je protilátka, -CEPT je vazebný receptor, -NIB je malá molekula inhibující kinázu.",
  [("🔤", "-mab = monoklonální protilátka"),
   ("🪝", "-cept = solubilní receptor (etanercept)"),
   ("🧩", "-nib = inhibitor kinázy (malá molekula)"),
   ("♻️", "BIOSIMILAR: podobný, nikdy ne identický")],
  [("Přípona -mab", "Monoklonální protilátka. Předposlední slabika říká původ: -xi- chimérická (infliximab), -zu- humanizovaná (trastuzumab), -u- plně lidská (adalimumab). Podávají se parenterálně — bílkovina by se v trávicím traktu strávila."),
   ("Přípona -cept", "Fúzní bílkovina, solubilní receptor, který na sebe naváže cytokin (etanercept váže TNF-α, abatacept, aflibercept)."),
   ("Přípona -nib", "Malá molekula, inhibitor kinázy — na rozdíl od protilátek se podává perorálně (imatinib, tofacitinib, ibrutinib)."),
   ("Biosimilar", "Biologicky podobný přípravek — u bílkoviny nelze vyrobit přesnou kopii jako u generika, proto se dokládá srovnatelná kvalita, účinnost a bezpečnost, ne pouhá bioekvivalence."),
   ("Rizika", "Infuzní a hypersenzitivní reakce, imunogenicita (tvorba protilátek proti léku), zvýšené riziko infekcí. ⚠️ Před anti-TNF-α je nutné vyloučit latentní tuberkulózu a hepatitidu B — hrozí reaktivace.")],
  "Biologika jsou bílkoviny — proto se nepodávají ústy, jsou drahá, vyžadují chladový řetězec a mohou vyvolat tvorbu neutralizujících protilátek, které je časem přestanou nechávat účinkovat.")

# ────────────────────────────── SPECIÁLNÍ FARMAKOLOGIE I ───────────────────────

S("36", "Cholinergní přenos vzruchu",
  "Acetylcholin má DVA typy zámků: NIKOTINOVÝ (rychlý, iontový kanál — ganglia a sval) a MUSKARINOVÝ (pomalý, přes G-protein — orgány).",
  [("🚬", "N receptory: ganglia + nervosvalová ploténka"),
   ("🍄", "M receptory: orgány parasympatiku, M1–M5"),
   ("✂️", "Acetylcholinesteráza ho ihned rozštěpí"),
   ("💧", "Účinek: SLUDGE — slinění, slzení, mióza")],
  [("Nikotinové", "Ionotropní — jsou samy iontovým kanálem, účinek za milisekundy. Nn v gangliích a dřeni nadledvin, Nm na nervosvalové ploténce."),
   ("Muskarinové", "Metabotropní, přes G-protein. M1 v CNS a gangliích, M2 v srdci (zpomalí ho), M3 v hladkém svalu a žlázách (kontrakce, sekrece)."),
   ("Nůžky", "Acetylcholin vzniká z cholinu a acetyl-CoA (cholinacetyltransferáza), po uvolnění ho okamžitě štěpí acetylcholinesteráza — proto je jeho účinek velmi krátký."),
   ("Účinky parasympatiku", "Mióza, akomodace na blízko, slzení a slinění, bradykardie, bronchokonstrikce a sekrece hlenu, zvýšená peristaltika, vyprázdnění močového měchýře.")],
  "Sympatikus i parasympatikus mají v gangliích tentýž nikotinový receptor — proto ganglioplegika ovlivňují obojí a mají tolik nežádoucích účinků.")

S("37", "Přímá cholinomimetika",
  "Přímé cholinomimetikum sedne rovnou na receptor. Účinek = všechno teče a všechno se stahuje: SLUDGE.",
  [("💧", "SLUDGE: slinění, slzení, moč, průjem, GIT, emeze"),
   ("👁️", "Pilokarpin: mióza, otevře úhel — glaukom"),
   ("🚽", "Bethanechol: atonie měchýře a střeva"),
   ("💊", "ANTIDOTUM: ATROPIN")],
  [("Kapky", "SLUDGE = salivation, lacrimation, urination, diarrhea, GI motility, emesis — typický muskarinový obraz."),
   ("Oko", "Pilokarpin je terciární amin z rostliny; stahuje musculus sphincter pupillae (mióza) a ciliární sval, čímž otevře komorový úhel — používá se u glaukomu s uzavřeným úhlem a u xerostomie po ozáření."),
   ("Měchýř", "Bethanechol — karbamátový ester, odolný vůči acetylcholinesteráze; stimuluje močový měchýř a střevo u pooperační atonie."),
   ("Atropin", "Antidotem předávkování je atropin. Karbachol se používá v oftalmologii; methacholin jen k bronchoprovokačnímu testu."),
   ("Kontraindikace", "Astma a CHOPN (bronchokonstrikce), vředová choroba, bradykardie a poruchy vedení, obstrukce močových cest a střeva.")],
  "Muskarin z muchomůrky červené a strmělek působí týž obraz — otrava se proto léčí atropinem.")

S("38", "Nepřímá cholinomimetika",
  "Nepřímé cholinomimetikum receptor nezná — jen ZABRÁNÍ ROZLOŽENÍ acetylcholinu, takže ho v synapsi zůstane víc.",
  [("✂️", "Blokují ACETYLCHOLINESTERÁZU"),
   ("💪", "Neostigmin: myasthenia gravis, dekurarizace"),
   ("🧠", "Donepezil, rivastigmin: Alzheimerova choroba"),
   ("☠️", "Organofosfáty: NEVRATNÁ blokáda")],
  [("Nůžky přeříznuté", "Inhibicí acetylcholinesterázy stoupá koncentrace acetylcholinu v synapsi — účinek je tedy nepřímý a závisí na vlastní produkci mediátoru."),
   ("Sval", "Neostigmin a pyridostigmin jsou kvartérní aminy — do CNS nepronikají; užívají se u myasthenia gravis, k dekurarizaci po nedepolarizujících myorelaxanciích a u pooperační atonie. Edrofonium má krátký účinek (dříve diagnostický test)."),
   ("Mozek", "Donepezil, rivastigmin a galantamin jsou terciární aminy — do CNS pronikají, používají se u Alzheimerovy choroby. Fysostigmin je antidotem anticholinergního deliria."),
   ("Lebka", "Organofosfáty (insekticidy, bojové látky) vážou enzym nevratně — vzniká cholinergní krize: mióza, bronchorea, bronchospasmus, bradykardie, křeče, obrna dýchacích svalů. Antidotem je ATROPIN (blokuje muskarinové účinky) + PRALIDOXIM (reaktivuje enzym, dokud nedojde ke „stárnutí“ vazby).")],
  "Atropin sám organofosfátovou otravu nevyřeší — neúčinkuje na nikotinové receptory, a tedy ani na obrnu dýchacích svalů. Proto se přidává pralidoxim.")

S("39", "Parasympatolytika",
  "Atropin dělá pravý opak SLUDGE: „SUCHÝ jako kost, RUDÝ jako řepa, HORKÝ jako pec, SLEPÝ jako netopýr, ŠÍLENÝ jako kloboučník.“",
  [("🏜️", "Sucho v ústech, zástava pocení"),
   ("👁️", "Mydriáza, porucha akomodace, ↑ nitrooční tlak"),
   ("💓", "Tachykardie, retence moči, zácpa"),
   ("🤪", "CNS: neklid, zmatenost, delirium")],
  [("Poušť", "Blokáda muskarinových receptorů — vysychají sliznice, ustane pocení, a tím stoupá teplota (u dětí nebezpečná hypertermie), kůže je suchá a zarudlá."),
   ("Oko", "Mydriáza a paralýza akomodace (cykloplegie); ⚠️ kontraindikací je glaukom s uzavřeným úhlem, protože rozšířená duhovka uzavře komorový úhel."),
   ("Srdce", "Tachykardie (blokáda M2), retence moči — proto pozor u hyperplazie prostaty — a zácpa až paralytický ileus."),
   ("Zástupci", "Atropin (bradykardie, premedikace, antidotum organofosfátů) · butylskopolamin (kvartérní, do CNS nepronikne — spasmolytikum) · ipratropium a tiotropium (inhalačně u CHOPN a astmatu) · tropikamid (oční vyšetření) · biperiden (léková parkinsonská symptomatika) · oxybutynin a solifenacin (hyperaktivní měchýř)."),
   ("Antidotum", "Fysostigmin — terciární amin, který proniká do CNS a zvrátí i centrální anticholinergní delirium.")],
  "Butylskopolamin je kvartérní amin, a proto neseduje ani nevyvolá delirium — atropin a skopolamin (terciární aminy) ano.")

S("40", "Adrenergní přenos vzruchu",
  "Noradrenalin se NEROZKLÁDÁ v synapsi jako acetylcholin — z 80 % se VYCHYTÁ ZPĚT do nervu. Proto na něj útočí kokain i tricyklika.",
  [("🔄", "Konec účinku = ZPĚTNÉ VYCHYTÁNÍ, ne rozklad"),
   ("🧬", "Tyrosin → DOPA → dopamin → noradrenalin → adrenalin"),
   ("🅰️", "α1 vazokonstrikce · α2 presynaptická brzda"),
   ("🅱️", "β1 srdce · β2 bronchy a cévy · β3 tuk a měchýř")],
  [("Kruh", "Účinek končí především zpětným vychytáváním (uptake-1) do nervového zakončení; teprve pak látku odbourává MAO a COMT. Kokain, tricyklika a SNRI tento transportér blokují."),
   ("Syntéza", "Tyrosin → DOPA (tyrosinhydroxyláza, krok určující rychlost) → dopamin → noradrenalin; v dřeni nadledvin dále na adrenalin."),
   ("Alfa", "α1 — vazokonstrikce, mydriáza, kontrakce svěrače měchýře a prostaty. α2 — presynapticky tlumí další výlev noradrenalinu (proto klonidin snižuje tlak centrálně)."),
   ("Beta", "β1 — srdce: zvýšená frekvence, vodivost a kontraktilita; v ledvině výlev reninu. β2 — bronchodilatace, vazodilatace ve svalech, relaxace dělohy, tremor, hypokalemie. β3 — lipolýza, relaxace detruzoru (mirabegron).")],
  "Adrenalin má afinitu ke všem receptorům, noradrenalin převážně k α a β1 (β2 skoro nestimuluje) — proto noradrenalin zvyšuje tlak vazokonstrikcí, kdežto adrenalin ve vyšší dávce navíc rozšiřuje bronchy.")

S("41", "Neselektivní sympatomimetika",
  "ADRENALIN je lék první volby u ANAFYLAXE — a to intramuskulárně do stehna. Žádné antihistaminikum ho nenahradí.",
  [("💉", "ANAFYLAXE: adrenalin i.m. do stehna"),
   ("🫁", "β2 → bronchodilatace · α1 → ustoupí edém"),
   ("❤️", "β1 → podpora srdce při zástavě a šoku"),
   ("💊", "S lokálním anestetikem: prodlouží účinek")],
  [("Stříkačka", "Adrenalin působí na α i β receptory. U anafylaxe se podává intramuskulárně do stehna (m. vastus lateralis) — nástup je rychlejší a bezpečnější než subkutánně."),
   ("Plíce", "β2 rozšíří bronchy, α1 stáhne cévy a ustoupí otok sliznice a angioedém — obojí zároveň, což žádný jiný lék neumí."),
   ("Srdce", "β1 zvyšuje kontraktilitu a frekvenci; adrenalin se podává při srdeční zástavě a v šoku. Vysoké dávky působí arytmie a hypertenzi."),
   ("Anestetikum", "Přídavek adrenalinu k lokálnímu anestetiku způsobí vazokonstrikci — zpomalí vstřebávání, prodlouží účinek a sníží krvácení a systémovou toxicitu."),
   ("Izoprenalin", "Neselektivní β-agonista (β1 i β2) — dnes okrajově u bradykardie a AV blokády. Dopamin a dobutamin patří k inotropní podpoře.")],
  "U pacienta na β-blokátoru může být adrenalin méně účinný — pak se u anafylaxe podává glukagon, který srdce stimuluje mimo β-receptor.")

S("42", "Sympatomimetika alfa",
  "α1 = STAHUJ CÉVY. Odtud obojí: zvýšení tlaku v šoku i zácpa nosu, která povolí — ale jen na pár dní, pak se vrátí hůř.",
  [("🩸", "α1: vazokonstrikce, ↑ periferní odpor"),
   ("👃", "Xylometazolin: jen 5–7 dní!"),
   ("🧠", "α2 CENTRÁLNĚ: klonidin SNIŽUJE tlak"),
   ("💓", "Reflexní bradykardie po vzestupu tlaku")],
  [("Céva", "α1-agonisté (fenylefrin, noradrenalin, midodrin) stahují cévy, zvyšují periferní odpor a krevní tlak — používají se v šoku, při hypotenzi a k lokální vazokonstrikci."),
   ("Nos", "Nosní dekongescencia (xylometazolin, oxymetazolin, nafazolin) stahují cévy sliznice. ⚠️ Jen 5–7 dní — jinak vzniká rhinitis medicamentosa s odrazovým otokem a závislostí na kapkách."),
   ("Mozek", "α2-agonisté (klonidin, methyldopa, brimonidin, dexmedetomidin) působí na PRESYNAPTICKÝ receptor v CNS — tlumí výlev noradrenalinu, a proto tlak SNIŽUJÍ. To je zdánlivý rozpor: agonista, který snižuje tlak."),
   ("Reflex", "Prudký vzestup tlaku vyvolá baroreflexem bradykardii — proto po fenylefrinu srdce zpomalí, ačkoli jde o sympatomimetikum.")],
  "Náhlé vysazení klonidinu vyvolá rebound hypertenzi s tachykardií a pocením — proto se vysazuje postupně.")

S("43", "Sympatomimetika beta",
  "β2 = ROZŠIŘ BRONCHY. Nežádoucí účinky jsou vždycky stejné trojice: TŘES, TACHYKARDIE, HYPOKALEMIE.",
  [("🫁", "SABA: salbutamol — úlevově, během minut"),
   ("⏳", "LABA: formoterol, salmeterol — jen s kortikoidem!"),
   ("🤲", "Tremor, tachykardie, hypokalemie"),
   ("🤰", "Tokolýza: hexoprenalin tlumí děložní stahy")],
  [("Plíce", "β2-agonisté relaxují hladký sval bronchu. SABA (salbutamol, fenoterol, terbutalin) působí během minut — úlevová léčba; vysoká spotřeba znamená špatně kontrolované astma."),
   ("Přesýpací hodiny", "LABA (formoterol, salmeterol, indakaterol) působí 12–24 hodin. ⚠️ Nikdy se nepodávají samostatně u astmatu — monoterapie LABA zvyšuje mortalitu; vždy v kombinaci s inhalačním kortikoidem."),
   ("Ruce", "Tremor (β2 v kosterním svalu), tachykardie (částečná stimulace β1 a reflexně), hypokalemie (draslík se přesouvá do buňky) — proto pozor při současné léčbě diuretiky a digoxinem."),
   ("Děloha", "β2-agonisté relaxují dělohu — hexoprenalin se používá k tokolýze při hrozícím předčasném porodu."),
   ("β1-agonisté", "Dobutamin — inotropní podpora u akutního srdečního selhání a kardiogenního šoku.")],
  "β2-agonista neléčí zánět, jen uvolní sval — proto astma nikdy nestojí na něm samotném, ale na inhalačním kortikoidu.")

S("44", "Nepřímá sympatomimetika",
  "Nepřímé sympatomimetikum na receptor nesedne — VYPLAVÍ noradrenalin ze zásob nebo zablokuje jeho zpětné vychytání. Zásoba se ale vyčerpá.",
  [("🪣", "Vyplavují noradrenalin ze zakončení"),
   ("🚫", "Blokují zpětné vychytávání (kokain, tricyklika)"),
   ("⚡", "TACHYFYLAXE: zásoba se vyčerpá, dávka nepomůže"),
   ("☠️", "S IMAO: HYPERTENZNÍ KRIZE (sýrový efekt)")],
  [("Kbelík", "Efedrin, pseudoefedrin, amfetamin a metamfetamin obracejí chod transportéru a vyplavují noradrenalin z nervového zakončení."),
   ("Zákaz", "Kokain, tricyklická antidepresiva a SNRI blokují zpětné vychytávání — mediátor zůstává v synapsi déle."),
   ("Blesk", "Opakované podání vyčerpá zásobu mediátoru → tachyfylaxe: účinek rychle slábne a zvýšení dávky nepomůže."),
   ("Lebka", "S inhibitory MAO hrozí hypertenzní krize — MAO nestačí odbourávat vyplavený noradrenalin. Týž mechanismus má „sýrový efekt“ po potravinách bohatých na tyramin (zrající sýry, uzeniny, červené víno)."),
   ("Použití", "Efedrin a pseudoefedrin jako dekongescencia a při hypotenzi; amfetaminové deriváty terapeuticky u ADHD a narkolepsie, jinak zneužívané.")],
  "Tyramin je nepřímé sympatomimetikum z potravy — normálně ho MAO ve střevě zlikviduje. Při léčbě IMAO se dostane do oběhu a vyplaví noradrenalin naráz.")

S("45", "Sympatolytika alfa",
  "α-blokáda uvolní cévy i hrdlo měchýře. Cena za to je PRVNÍ DÁVKA VESTOJE = pád — proto se první tableta bere na noc.",
  [("📉", "Vazodilatace → pokles tlaku"),
   ("🛏️", "Fenomén první dávky: ortostatická hypotenze"),
   ("🚹", "Tamsulosin: uroselektivní, hyperplazie prostaty"),
   ("👁️", "IFIS: syndrom plovoucí duhovky při operaci katarakty")],
  [("Pokles", "Blokáda α1 uvolní hladký sval cév — klesá periferní odpor a tlak. Neselektivní doxazosin a terazosin se používají u hypertenze i u prostaty."),
   ("Postel", "Fenomén první dávky — prudká ortostatická hypotenze a synkopa; proto se začíná nízkou dávkou na noc."),
   ("Prostata", "Tamsulosin a silodosin jsou uroselektivní (α1A) — uvolní hladký sval prostaty a hrdla měchýře, tlak ovlivní málo. Nežádoucí je retrográdní ejakulace."),
   ("Oko", "⚠️ IFIS (intraoperative floppy iris syndrome) — před operací katarakty je nutné oftalmologa upozornit na užívání tamsulosinu."),
   ("Fenoxybenzamin a fentolamin", "Neselektivní α-blokátory používané u feochromocytomu — podávají se před β-blokátorem, jinak by nebrzděná α-stimulace vyvolala hypertenzní krizi.")],
  "U feochromocytomu se nikdy nezačíná β-blokátorem. Nejprve α-blokáda, teprve pak β — jinak zůstane vazokonstrikce bez protiváhy.")

S("46", "Sympatolytika beta (betablokátory)",
  "β-blokátor zpomalí a zklidní srdce. Ale nekardioselektivní blokuje i β2 — a tím STÁHNE BRONCHY. Proto u astmatu pozor.",
  [("💓", "↓ frekvence, kontraktilita, spotřeba kyslíku"),
   ("🫁", "Neselektivní blokují i β2 → bronchospasmus"),
   ("🍬", "Maskují příznaky HYPOGLYKEMIE (kromě pocení)"),
   ("⛔", "NEVYSAZOVAT NÁHLE — rebound, riziko infarktu")],
  [("Srdce", "Blokáda β1 snižuje frekvenci, kontraktilitu, vodivost a spotřebu kyslíku myokardem; snižuje i výlev reninu. Indikace: hypertenze, ischemická choroba, arytmie, srdeční selhání (bisoprolol, karvedilol, metoprolol), tyreotoxikóza, tremor, migréna, glaukom."),
   ("Plíce", "Neselektivní (propranolol, sotalol) blokují i β2 — bronchospasmus a periferní vazokonstrikce. Kardioselektivní (bisoprolol, metoprolol, atenolol, nebivolol) jsou bezpečnější, ale selektivita ve vysoké dávce mizí."),
   ("Cukr", "U diabetika maskují varovné příznaky hypoglykemie (tachykardii, třes) — pocení zůstává; a zpomalují úpravu glykemie."),
   ("Zákaz náhlého vysazení", "Při dlouhé blokádě dojde k up-regulaci receptorů; náhlé vysazení vyvolá rebound tachykardii, hypertenzi a může vyprovokovat anginu nebo infarkt. Vysazuje se postupně."),
   ("Zvláštní", "Karvedilol a labetalol blokují i α1. Sotalol má navíc antiarytmický účinek III. třídy. Nebivolol uvolňuje oxid dusnatý.")],
  "⚠️ Kombinace β-blokátoru s verapamilem nebo diltiazemem hrozí těžkou bradykardií a AV blokádou — obě skupiny tlumí převodní systém.")

S("47", "Myorelaxancia",
  "DEPOLARIZUJÍCÍ nejprve SVAL ROZKMITÁ (fascikulace) a pak ochrne — a dekurarizovat se NEDÁ. Nedepolarizující se zvrátit dá.",
  [("⚡", "Sukcinylcholin: fascikulace → paralýza, 5–10 min"),
   ("🚫", "Nedepolarizující: rokuronium, atrakurium — kompetitivní"),
   ("💊", "Zvrat: neostigmin, sugammadex (jen na rokuronium)"),
   ("🔥", "MALIGNÍ HYPERTERMIE → dantrolen")],
  [("Fascikulace", "Sukcinylcholin je depolarizující — chová se jako acetylcholin, který se nerozkládá; nejprve receptor trvale aktivuje (viditelné záškuby), pak nastane blokáda. Působí 5–10 minut, štěpí ho plazmatická cholinesteráza."),
   ("Kompetice", "Nedepolarizující (rokuronium, vekuronium, atrakurium, cisatrakurium) jsou kompetitivní antagonisté nikotinového receptoru na ploténce — sval ochrne bez fascikulací."),
   ("Zvrat", "Nedepolarizující blok lze zvrátit neostigmimem (zvýší acetylcholin) nebo u rokuronia specificky sugammadexem. ⚠️ Depolarizující blok zvrátit nelze — neostigmin by ho prohloubil."),
   ("Oheň", "Maligní hypertermie — vzácná geneticky podmíněná reakce na sukcinylcholin a inhalační anestetika: prudký vzestup teploty, rigidita, acidóza. Antidotem je DANTROLEN."),
   ("Další rizika sukcinylcholinu", "Hyperkalemie (nebezpečná u popálenin, polytraumat a neuromuskulárních chorob), bolest svalů, vzestup nitroočního tlaku, prodloužená apnoe při atypické pseudocholinesteráze."),
   ("Centrální myorelaxancia", "Baklofen (agonista GABA-B), tizanidin, tolperison — na spasticitu, nikoli k anestezii.")],
  "Myorelaxans netlumí vědomí ani bolest — pacient musí být zároveň uspán a analgetizován, jinak je ochrnutý při vědomí.")

S("48", "Lokální anestetika",
  "Blokují SODÍKOVÝ KANÁL zevnitř. V zánětu (kyselé pH) převáží nabitá forma, která dovnitř neprojde — proto tam nezabírají.",
  [("🚪", "Blokáda Na+ kanálu → nevznikne akční potenciál"),
   ("🔥", "V zánětu nezabírají (kyselé pH)"),
   ("💉", "S adrenalinem: déle a méně krvácení"),
   ("🧠", "Toxicita: nejdřív CNS (křeče), pak SRDCE")],
  [("Kanál", "Vážou se zevnitř na napěťově řízený sodíkový kanál a brání vzniku a šíření akčního potenciálu. Nejdřív vypadne bolest a teplo, pak dotek, nakonec motorika (tenká nemyelinizovaná vlákna první)."),
   ("Zánět", "Anestetikum je slabá zásada; v kyselém prostředí zánětu převáží ionizovaná forma, která neprojde membránou k místu účinku uvnitř kanálu — proto se v zaníceném terénu často nepodaří umrtvit."),
   ("Adrenalin", "Vazokonstrikce zpomalí vstřebávání: prodlouží účinek, sníží krvácení a systémovou toxicitu. ⚠️ Nepodává se do akrálních částí (prsty, nos, ucho) — riziko ischemie."),
   ("Toxicita", "Systémová toxicita začíná v CNS: kovová chuť, brnění kolem úst, hučení, závrať, křeče — a teprve pak přijde kardiotoxicita (arytmie, zástava). Bupivakain je nejkardiotoxičtější; léčbou je lipidová emulze."),
   ("Skupiny", "Estery (prokain, benzokain, tetrakain) — štěpí je plazmatické esterázy, častější alergie (metabolit PABA). Amidy (lidokain, mepivakain, artikain, bupivakain, prilokain) — metabolizují se v játrech, alergie vzácná.")],
  "Prilokain a benzokain mohou vyvolat methemoglobinemii (antidotem je methylenová modř). Lidokain je zároveň antiarytmikum třídy Ib.")

S("49", "Celková anestetika — inhalační",
  "MAC je „dávka“ inhalačního anestetika: koncentrace, při níž se polovina pacientů nepohne. Čím NIŽŠÍ MAC, tím SILNĚJŠÍ látka.",
  [("📊", "MAC = minimální alveolární koncentrace"),
   ("💨", "Nízká rozpustnost v krvi = rychlý nástup i probuzení"),
   ("🔥", "MALIGNÍ HYPERTERMIE → dantrolen"),
   ("😀", "Oxid dusný: silná analgezie, slabá anestezie")],
  [("Graf", "MAC — koncentrace, při níž se 50 % pacientů nepohne po kožním řezu; je mírou potence. Nízké MAC = vysoká potence. MAC klesá s věkem, v graviditě a při současném podání opioidů."),
   ("Pára", "Rychlost nástupu určuje rozpustnost v krvi (koeficient krev/plyn): čím je nižší, tím rychleji stoupá alveolární koncentrace a tím rychlejší je nástup i probuzení. Desfluran a sevofluran nastupují rychle, halothan pomalu."),
   ("Oheň", "⚠️ Halogenovaná anestetika (sevofluran, desfluran, isofluran) mohou spolu se sukcinylcholinem vyvolat malignitní hypertermii — antidotem je dantrolen. Halothan navíc hepatotoxicitu."),
   ("Rajský plyn", "Oxid dusný (N2O) má výbornou analgezii, ale slabý anestetický účinek — používá se jako doplněk. Inaktivuje vitamin B12 (megaloblastová anemie a neuropatie při dlouhé expozici) a difunduje do uzavřených dutin.")],
  "Inhalační anestetika snižují krevní tlak a tlumí dýchání; sevofluran je pro dobrou snášenlivost dýchacími cestami vhodný k úvodu do anestezie u dětí.")

S("50", "Celková anestetika — intravenózní",
  "PROPOFOL uspí i probudí rychle. KETAMIN je výjimka ze všech pravidel: tlak a dech NEKLESAJÍ, analgezie je silná — ale probouzí se z něj s halucinacemi.",
  [("🥛", "Propofol: rychlý úvod, „mléko“, ↓ tlak"),
   ("🌀", "Ketamin: disociativní, NMDA antagonista"),
   ("🫀", "Etomidát: oběhově stabilní, tlumí kortizol"),
   ("💤", "Thiopental: rychlé probuzení REDISTRIBUCÍ")],
  [("Propofol", "Nejužívanější — rychlý nástup i odeznění, antiemetický účinek. Nežádoucí: pokles krevního tlaku, útlum dechu, bolest při injekci; při dlouhé vysokodávkované infuzi propofolový infuzní syndrom."),
   ("Ketamin", "Antagonista NMDA receptoru; vyvolá disociativní anestezii se silnou analgezií. ⚠️ Na rozdíl od ostatních neklesá krevní tlak (stoupá) ani dechová aktivita — proto se hodí v šoku a v přednemocniční péči. Nežádoucí jsou halucinace a neklid při probouzení (tlumí je benzodiazepin). Esketamin se používá u farmakorezistentní deprese."),
   ("Etomidát", "Oběhově velmi stabilní — vhodný u kardiaka; tlumí ale syntézu kortizolu v nadledvině, proto se nepodává v infuzi."),
   ("Thiopental", "Barbiturát; účinek končí REDISTRIBUCÍ do svalu a tuku, nikoli eliminací — proto se pacient probudí rychle, ale látka v těle přetrvává a při opakovaném podání se kumuluje.")],
  "Anestezie se v praxi vede kombinací: hypnotikum + analgetikum (opioid) + myorelaxans. Jedna látka nezvládne všechny tři složky současně.")

S("51", "Hypnotika",
  "Z-hypnotika i benzodiazepiny sedají na TÝŽ GABA-A receptor — proto mají stejná rizika: pády, závislost, rebound nespavost.",
  [("😴", "Z-léčiva: zolpidem, zopiklon — jen na usnutí"),
   ("🔗", "Vážou GABA-A (ω1 podjednotka)"),
   ("🌙", "Melatoninergní: melatonin, ramelteon — bezpečné"),
   ("⚠️", "Krátce! Závislost, pády, rebound insomnie")],
  [("Spánek", "Z-hypnotika (zolpidem, zopiklon, zaleplon) zkracují dobu usnutí; mají krátký poločas, takže ráno méně tlumí než benzodiazepiny. Nežádoucí: amnézie, parasomnie (jízda a jedení ve spánku), pády u seniorů."),
   ("Receptor", "Vážou se selektivně na ω1 podjednotku GABA-A receptoru — proto působí hypnoticky, ale mnohem méně anxiolyticky, myorelaxačně a antikonvulzivně než benzodiazepiny. Antidotem je flumazenil."),
   ("Měsíc", "Melatonin a agonisté melatoninových receptorů upravují cirkadiánní rytmus; jsou bezpečné, nenávykové, ale slabší. Antihistaminika I. generace (prometazin, difenhydramin) sedují za cenu anticholinergních účinků."),
   ("Varování", "Podávat co nejkratší dobu; po vysazení hrozí rebound nespavost. Základem léčby nespavosti je spánková hygiena a kognitivně-behaviorální terapie, ne tableta.")],
  "Barbituráty se dnes jako hypnotika nepoužívají — mají úzké terapeutické okno, prohlubují útlum dechu bez stropu a silně indukují CYP450.")

S("52", "Benzodiazepiny",
  "Benzodiazepin ZVÝŠÍ FREKVENCI otevírání chloridového kanálu — ale jen tam, kde už GABA je. Proto má strop a sám o sobě nezabíjí.",
  [("🚪", "↑ FREKVENCE otevření kanálu (barbiturát ↑ DOBU)"),
   ("🎯", "Anxiolytikum, hypnotikum, antikonvulzivum, myorelaxans"),
   ("🍷", "S ALKOHOLEM a OPIOIDY: útlum dechu"),
   ("💉", "Antidotum FLUMAZENIL — opatrně, hrozí křeče")],
  [("Kanál", "Benzodiazepiny se vážou na alosterické místo GABA-A receptoru a zvyšují FREKVENCI otevírání chloridového kanálu; barbituráty zvyšují DOBU otevření a ve vysoké dávce kanál otevřou i bez GABA — proto nemají strop a jsou nebezpečnější."),
   ("Čtyři účinky", "Anxiolytický, hypnotický, antikonvulzivní (lék volby u status epilepticus — diazepam, midazolam) a centrálně myorelaxační; dále anterográdní amnézie (využívá se při výkonech)."),
   ("Alkohol", "⚠️ Samotný benzodiazepin dech tlumí málo, ale v kombinaci s alkoholem, opioidy nebo Z-léčivy hrozí smrtelný útlum dechu — to je nejčastější příčina úmrtí."),
   ("Flumazenil", "Kompetitivní antagonista; u chronického uživatele nebo při smíšené intoxikaci s tricykliky může vyvolat křeče, proto se podává uvážlivě."),
   ("Zástupci", "Krátce působící midazolam · středně alprazolam, oxazepam, lorazepam (u jaterní léze — jen konjugace) · dlouze diazepam, klonazepam. Odvykací stav je nebezpečný (křeče, delirium) — vysazuje se pomalu.")],
  "U seniorů se preferují krátkodobě působící a jen krátce — dlouhodobě působící benzodiazepiny jsou na seznamu nevhodných léčiv (pády, zmatenost, zlomeniny krčku).")

S("53", "Antiepileptika",
  "Antiepileptikum brzdí nadměrné výboje: zavře SODÍKOVÝ kanál, nebo posílí GABA. A skoro všechna jsou TERATOGENNÍ — hlavně valproát.",
  [("🚪", "Blokáda Na+ kanálu: fenytoin, karbamazepin, lamotrigin"),
   ("🧘", "Posílení GABA: benzodiazepiny, fenobarbital, valproát"),
   ("🤰", "VALPROÁT: nejsilnější teratogen — rozštěpy, ↓ IQ"),
   ("⚠️", "Lamotrigin: pomalu titrovat — SJS")],
  [("Kanál", "Blokáda napěťově řízených sodíkových kanálů brzdí opakované výboje — fenytoin (saturační kinetika, gingivální hyperplazie, hirsutismus), karbamazepin (indukce CYP450, hyponatremie, agranulocytóza), lamotrigin, lakosamid."),
   ("Klid", "Posílení GABA — benzodiazepiny, fenobarbital, valproát, tiagabin, vigabatrin. Ethosuximid blokuje kalciové kanály typu T a je lékem volby u absencí."),
   ("Gravidita", "⚠️ Valproát je nejsilnější teratogen mezi antiepileptiky (rozštěpy neurální trubice, poruchy vývoje a snížení IQ) — u žen ve fertilním věku se podává jen výjimečně a se spolehlivou kontracepcí. Podává se kyselina listová."),
   ("Vyrážka", "Lamotrigin se musí titrovat velmi pomalu — jinak hrozí Stevensův–Johnsonův syndrom; riziko roste při současném valproátu, který jeho hladinu zvyšuje."),
   ("Status epilepticus", "Lékem první volby je benzodiazepin (diazepam, midazolam, lorazepam), dále fenytoin nebo valproát nitrožilně.")],
  "Karbamazepin je silný induktor CYP450 — sníží účinnost hormonální kontracepce, warfarinu a mnoha dalších léčiv. Valproát je naopak inhibitor.")

S("54", "Antiparkinsonika",
  "V parkinsonském mozku CHYBÍ DOPAMIN a převáží acetylcholin. Dopamin sám se podat nedá — neprojde do mozku, proto se dává LEVODOPA.",
  [("🚧", "Dopamin neprojde bariérou → podává se LEVODOPA"),
   ("🛡️", "S karbidopou: brání rozkladu na periferii"),
   ("🎢", "Po letech: wearing-off, on-off, dyskineze"),
   ("⚖️", "Agonisté dopaminu: impulzivní chování, spavost")],
  [("Bariéra", "Dopamin neprochází hematoencefalickou bariérou; levodopa ano a v mozku se dekarboxyluje na dopamin."),
   ("Štít", "Kombinuje se s inhibitorem periferní dekarboxylázy (karbidopa, benserazid) — jinak by se rozložila v těle a způsobila nauzeu, zvracení a hypotenzi. Dále inhibitory COMT (entakapon) a MAO-B (selegilin, rasagilin), které prodlouží její účinek."),
   ("Horská dráha", "Po několika letech léčby se objevuje kolísání účinku (wearing-off, on-off fenomén) a polékové dyskineze — proto se u mladších začíná agonisty dopaminu a levodopa se oddaluje."),
   ("Agonisté", "Pramipexol, ropinirol, rotigotin. ⚠️ Typickým nežádoucím účinkem jsou poruchy impulzivního chování (hráčství, nakupování, hypersexualita) a náhlé usnutí — na to je nutné pacienta upozornit."),
   ("Anticholinergika", "Biperiden — pomáhá hlavně na třes, ale u starších působí zmatenost. Amantadin tlumí dyskineze.")],
  "Antipsychotika blokující D2 receptory vyvolají polékový parkinsonský syndrom — a naopak levodopa může u disponovaných vyvolat psychózu. Metoklopramid ze stejného důvodu u parkinsonika nepodávat.")

S("55", "Neuroleptika (antipsychotika)",
  "Klasická blokují D2 tvrdě → EXTRAPYRAMIDOVÉ nežádoucí účinky. Atypická blokují i 5-HT2A → méně hybných potíží, zato METABOLICKÝ syndrom.",
  [("🚫", "Blokáda D2 v mezolimbické dráze → ↓ pozitivní příznaky"),
   ("🤖", "Klasická: dystonie, parkinsonismus, akatizie, tardivní dyskineze"),
   ("🍔", "Atypická: přírůstek hmotnosti, diabetes, dyslipidemie"),
   ("🔥", "NEUROLEPTICKÝ MALIGNÍ SYNDROM → dantrolen")],
  [("Blokáda", "Účinek na pozitivní příznaky (halucinace, bludy) plyne z blokády D2 v mezolimbické dráze; blokáda v nigrostriatální dráze působí hybné potíže a v tuberoinfundibulární hyperprolaktinemii (galaktorea, amenorea, gynekomastie)."),
   ("Robot", "Extrapyramidové projevy klasických (haloperidol, flufenazin, chlorpromazin): akutní dystonie (hodiny až dny), parkinsonský syndrom, akatizie (neklid) a po letech tardivní dyskineze, která bývá nevratná."),
   ("Metabolika", "Atypická (olanzapin, klozapin, risperidon, kvetiapin, aripiprazol) blokují navíc 5-HT2A — méně hybných potíží, ale přírůstek hmotnosti, diabetes 2. typu a dyslipidemie. ⚠️ Klozapin působí AGRANULOCYTÓZU — nutné pravidelné kontroly krevního obrazu; je vyhrazen farmakorezistentní schizofrenii."),
   ("Oheň", "Neuroleptický maligní syndrom — horečka, svalová rigidita, porucha vědomí, vzestup kreatinkinázy. Léčba: vysadit neuroleptikum, dantrolen, bromokriptin, podpůrná péče."),
   ("Další", "Prodloužení QT (zvláště haloperidol, ziprasidon), sedace, ortostatická hypotenze, anticholinergní účinky.")],
  "Negativní příznaky (oploštění, apatie) reagují na léčbu podstatně hůř než pozitivní — a klasická neuroleptika je mohou dokonce zhoršit.")

S("56", "Antidepresiva — tricyklická, inhibitory MAO",
  "Tricyklika fungují, ale trefí se do všeho: do histaminu (sedace), do muskarinu (sucho, retence) i do α1 (pády). A při předávkování ZABÍJEJÍ.",
  [("🎯", "Blokáda zpětného vychytávání NA i 5-HT"),
   ("🏜️", "Anticholinergně: sucho, retence, zácpa, zmatenost"),
   ("💔", "Předávkování: ARYTMIE, křeče — malá terapeutická šíře"),
   ("🧀", "IMAO + tyramin = HYPERTENZNÍ KRIZE")],
  [("Terč", "Tricyklika (amitriptylin, klomipramin, imipramin, nortriptylin) blokují zpětné vychytávání noradrenalinu i serotoninu — účinná, ale málo selektivní."),
   ("Poušť", "Blokují navíc muskarinové receptory (sucho v ústech, rozmazané vidění, zácpa, retence moči, u seniorů zmatenost), H1 (sedace, přírůstek hmotnosti) a α1 (ortostatická hypotenze, pády)."),
   ("Srdce", "⚠️ Při předávkování působí blokádou sodíkových kanálů arytmie, rozšíření QRS, křeče a kóma — proto se u suicidálního pacienta nepředepisují ve velkém balení. Dnes se používají spíš u neuropatické bolesti a v profylaxi migrény."),
   ("Sýr", "Ireverzibilní neselektivní IMAO (tranylcypromin) — při požití potravin bohatých na tyramin (zrající sýry, uzeniny, červené víno) hrozí hypertenzní krize. Moklobemid je reverzibilní selektivní inhibitor MAO-A, a proto podstatně bezpečnější."),
   ("Serotoninový syndrom", "⚠️ Kombinace IMAO s SSRI, tramadolem nebo triptany — horečka, rigidita, myoklonus, neklid; mezi IMAO a SSRI je nutná několikatýdenní pauza.")],
  "Antidepresivní účinek nastupuje až za 2–4 týdny, zatímco nežádoucí účinky hned první den — to je nejčastější důvod, proč pacient léčbu předčasně ukončí.")

S("57", "Antidepresiva — SSRI, SNRI, atypická",
  "SSRI jsou dnes první volbou ne proto, že by byla účinnější, ale protože jsou BEZPEČNĚJŠÍ — hlavně při předávkování.",
  [("🎯", "SSRI: selektivně blokují zpětné vychytávání serotoninu"),
   ("📅", "Účinek až za 2–4 TÝDNY, nežádoucí hned"),
   ("⚠️", "SEROTONINOVÝ SYNDROM při kombinacích"),
   ("🩸", "S NSA a antiagregancii: riziko krvácení")],
  [("Terč", "SSRI (sertralin, escitalopram, citalopram, fluoxetin, paroxetin, fluvoxamin) blokují serotoninový transportér. Nežádoucí: nauzea, nespavost nebo útlum, sexuální dysfunkce (velmi častá), hyponatremie u seniorů, na začátku zvýšení úzkosti."),
   ("Kalendář", "Nástup účinku 2–4 týdny; na začátku léčby může přechodně stoupnout riziko sebevražedného jednání u mladých — proto se první týdny sleduje častěji."),
   ("Serotoninový syndrom", "⚠️ Při kombinaci s IMAO, tramadolem, triptany, linezolidem nebo třezalkou: horečka, rigidita, myoklonus, průjem, neklid až kóma."),
   ("Krvácení", "SSRI snižují vychytávání serotoninu i do destiček — spolu s NSA nebo antiagregancii roste riziko krvácení do trávicího traktu."),
   ("SNRI a atypická", "Venlafaxin a duloxetin (serotonin + noradrenalin; duloxetin i u diabetické neuropatie) · mirtazapin (sedativní, zvyšuje chuť k jídlu — vhodný u nespavosti a kachexie) · bupropion (dopamin a noradrenalin, snižuje práh křečí, pomáhá při odvykání kouření) · trazodon · agomelatin. ⚠️ Fluoxetin a paroxetin jsou silné inhibitory CYP2D6 — sníží účinek kodeinu a tamoxifenu.")],
  "SSRI se nevysazují náhle (kromě fluoxetinu s dlouhým poločasem) — hrozí syndrom z vysazení: závratě, „elektrické šoky“, úzkost, chřipkovité příznaky.")

S("58", "Anxiolytika, stabilizátory nálady",
  "LITHIUM má tak úzké terapeutické okno, že se hladiny MĚŘÍ POVINNĚ — a dehydratace, NSA nebo ACE inhibitor ho vyženou do toxicity.",
  [("📏", "Lithium: úzké okno, POVINNÉ měření hladin"),
   ("🚰", "Dehydratace, NSA, diuretika, ACEi → ↑ hladina"),
   ("🦋", "Hypotyreóza, tremor, polyurie, ↑ hmotnost"),
   ("💊", "Alternativy: valproát, lamotrigin, karbamazepin")],
  [("Pravítko", "Lithium se používá u bipolární afektivní poruchy — jako jediné prokazatelně snižuje riziko sebevraždy. Terapeutické rozmezí je velmi úzké, proto se hladiny sledují pravidelně."),
   ("Voda", "Vylučuje se výhradně ledvinami a soupeří se sodíkem — při dehydrataci, zvracení, průjmu, dietě s omezením soli a při současném podání NSA, thiazidů nebo ACE inhibitorů hladina prudce stoupá. Intoxikace: třes, zvracení, ataxie, zmatenost, křeče."),
   ("Motýl", "Dlouhodobě působí hypotyreózu (sledovat TSH), nefrogenní diabetes insipidus s polyurií a žízní, tremor, přírůstek hmotnosti. ⚠️ Je teratogenní (Ebsteinova anomálie)."),
   ("Alternativy", "Valproát (u mánie, ⚠️ teratogenní), lamotrigin (spíš na depresivní fázi), karbamazepin, atypická antipsychotika (kvetiapin, olanzapin, aripiprazol)."),
   ("Anxiolytika", "Benzodiazepiny jen krátkodobě · buspiron (agonista 5-HT1A, nenávykový, ale pomalý nástup) · hydroxyzin · pro dlouhodobou léčbu úzkostných poruch jsou lékem volby SSRI a SNRI, ne benzodiazepiny.")],
  "U bipolární poruchy se antidepresivum nikdy nepodává samo — může přesmyknout pacienta do mánie; podává se pod clonou stabilizátoru nálady.")

S("59", "Farmakoterapie Alzheimerovy choroby, nootropika",
  "Léčba Alzheimerovy choroby nemoc NEZASTAVÍ — jen na čas zmírní příznaky. Chybí acetylcholin, tak se brzdí jeho rozklad.",
  [("✂️", "Inhibitory acetylcholinesterázy: donepezil, rivastigmin"),
   ("🧠", "Memantin: antagonista NMDA — středně těžká až těžká"),
   ("💧", "Cholinergní NÚ: nauzea, průjem, bradykardie"),
   ("❓", "Nootropika: účinnost slabě doložená")],
  [("Nůžky", "Donepezil, rivastigmin a galantamin zvyšují množství acetylcholinu v CNS; jsou indikovány u lehké až středně těžké formy. Zlepší kognici a soběstačnost dočasně, progresi nezastaví."),
   ("Mozek", "Memantin je antagonista NMDA receptoru — chrání před excitotoxicitou glutamátu; používá se u středně těžké až těžké formy, lze kombinovat."),
   ("Kapka", "Nežádoucí účinky vyplývají z cholinergní stimulace: nauzea, zvracení, průjem, nechutenství, bradykardie a synkopy (opatrnost u poruch vedení), noční můry, svalové křeče."),
   ("Otazník", "Nootropika (piracetam, ginkgo biloba, extrakty) mají důkazy o účinnosti slabé; nenahrazují výše uvedenou léčbu."),
   ("Nefarmakologicky", "Kognitivní trénink, pohyb, léčba přidružených chorob a úprava prostředí; u poruch chování se antipsychotika podávají jen krátce a v nízké dávce — ⚠️ u demence zvyšují mortalitu a riziko cévní mozkové příhody.")],
  "Anticholinergní léčiva (antihistaminika I. generace, tricyklika, oxybutynin) kognici u demence zhoršují — působí přesně proti nasazené léčbě.")

S("60", "Opium a jeho alkaloidy",
  "MORFIN má jednu vlastnost, která ho dělá nebezpečným: tolerance na euforii a útlum dechu roste rychle, ale na ZÁCPU a MIÓZU prakticky vůbec.",
  [("💤", "μ-receptor: analgezie, euforie, útlum dechu"),
   ("👁️", "MIÓZA (špendlíkové zornice) — tolerance nevzniká"),
   ("🚽", "ZÁCPA — tolerance nevzniká, léčí se vždy"),
   ("💉", "ANTIDOTUM: NALOXON")],
  [("Útlum", "Morfin je agonista μ-opioidních receptorů: silná analgezie, euforie, sedace, útlum kašle — a útlum dechového centra, který je hlavní příčinou smrti při předávkování."),
   ("Zornice", "Mióza je klíčovým příznakem otravy a na rozdíl od ostatních účinků na ni nevzniká tolerance; triáda otravy je útlum vědomí + útlum dechu + mióza."),
   ("Zácpa", "Vzniká zpomalením peristaltiky přes periferní μ-receptory; tolerance na ni prakticky nevzniká, proto se laxativum podává profylakticky po celou dobu léčby opioidem."),
   ("Naloxon", "Kompetitivní antagonista; působí krátce, proto je nutné opakované podání a sledování — jinak se útlum dechu vrátí. U závislého vyvolá odvykací stav."),
   ("Další alkaloidy opia", "Kodein (proléčivo, CYP2D6 → morfin; antitusikum), papaverin (myotropní spasmolytikum, není analgetikum), thebain (výchozí látka pro polosyntetické opioidy).")],
  "Další nežádoucí účinky: nauzea a zvracení (stimulace area postrema), retence moči, svědění a uvolnění histaminu, biliární spasmus. U bolesti při kolice se proto morfin kombinuje se spasmolytikem.")

S("61", "Deriváty a náhražky morfinu",
  "Parciální agonista (BUPRENORFIN) má STROP — víc už nepřidá. A když ho dáš na plného agonistu, VYTLAČÍ ho a vyvolá odvykací stav.",
  [("🪜", "Buprenorfin: parciální agonista, má strop"),
   ("💪", "Fentanyl: 100× silnější než morfin, náplast"),
   ("🔀", "Tramadol: opioid + serotonin — riziko křečí"),
   ("🔄", "Metadon: substituce, dlouhý poločas, ↑ QT")],
  [("Žebřík", "Buprenorfin je parciální agonista μ — má stropový efekt (bezpečnější útlum dechu), ale vysokou afinitu; podaný na plného agonistu ho vytěsní a vyvolá odvykací stav. Používá se v substituční léčbě a transdermálně u chronické bolesti."),
   ("Síla", "Fentanyl je asi 100× potentnější než morfin — transdermální náplast u chronické nádorové bolesti, i.v. v anestezii. Sufentanil a remifentanil jsou ještě silnější a kratší."),
   ("Tramadol", "Slabý opioidní agonista, který navíc blokuje zpětné vychytávání serotoninu a noradrenalinu. ⚠️ Snižuje práh křečí a s SSRI hrozí serotoninový syndrom; je proléčivo aktivované CYP2D6."),
   ("Metadon", "Dlouhý a proměnlivý poločas — vhodný k substituci u závislosti, ale hrozí kumulace a prodloužení QT."),
   ("Další", "Piritramid, oxykodon (často s naloxonem proti zácpě), hydromorfon, pethidin (metabolit norpethidin je neurotoxický — dnes se nedoporučuje), nalbufin a pentazocin (agonisté-antagonisté).")],
  "Naltrexon je dlouhodobě působící antagonista užívaný v udržovací léčbě závislosti (i na alkoholu); naloxon slouží akutně při předávkování.")

S("62", "Eikosanoidy",
  "Z kyseliny arachidonové vedou DVĚ cesty: COX dělá prostaglandiny, LOX leukotrieny. Kortikoid zavře OBĚ, NSA jen tu první.",
  [("🔱", "Kyselina arachidonová = společný výchozí bod"),
   ("🌡️", "COX → prostaglandiny, prostacyklin, tromboxan"),
   ("🫁", "LOX → leukotrieny (bronchokonstrikce)"),
   ("🛑", "Kortikoid blokuje fosfolipázu A2 = obě cesty")],
  [("Rozcestí", "Fosfolipáza A2 uvolní z membrány kyselinu arachidonovou; z ní vycházejí dvě větve."),
   ("COX", "Cyklooxygenáza tvoří prostaglandiny (zánět, bolest, horečka, ochrana žaludeční sliznice, průtok ledvinami), prostacyklin PGI2 (vazodilatace, brzdí agregaci — z endotelu) a tromboxan TXA2 (vazokonstrikce, podporuje agregaci — z destiček). COX-1 je konstitutivní (ochranná), COX-2 indukovaná zánětem."),
   ("LOX", "Lipoxygenáza tvoří leukotrieny — silná bronchokonstrikce, zvýšená propustnost cév a chemotaxe; odtud montelukast u astmatu."),
   ("Kortikoid", "Glukokortikoidy inhibují fosfolipázu A2 (přes lipokortin), a tím zavřou obě větve — proto jsou protizánětlivě účinnější než NSA."),
   ("Léčebné využití", "Misoprostol (analog PGE1 — ochrana žaludku, ⚠️ kontraindikován v graviditě), latanoprost (glaukom), alprostadil, dinoproston (indukce porodu), epoprostenol (plicní hypertenze).")],
  "Aspirinem indukované astma vzniká právě tady: zablokovaná COX odkloní kyselinu arachidonovou do LOX větve a vzniká nadbytek leukotrienů.")

S("63", "Analgetika-antipyretika",
  "PARACETAMOL v terapeutické dávce nedráždí žaludek a neruší srážení — ale při předávkování ZNIČÍ JÁTRA. Hranice je blíž, než se čeká.",
  [("🌡️", "Tlumí bolest a horečku, protizánětlivě téměř ne"),
   ("🫀", "Nevadí žaludku ani destičkám — volba v graviditě"),
   ("☠️", "Předávkování → NAPQI → jaterní nekróza"),
   ("💊", "ANTIDOTUM: N-ACETYLCYSTEIN")],
  [("Teploměr", "Paracetamol působí centrálně (COX v CNS) — analgeticky a antipyreticky; protizánětlivý účinek prakticky nemá, na rozdíl od NSA."),
   ("Bezpečnost", "Nedráždí žaludeční sliznici, neovlivňuje agregaci destiček a nezhoršuje astma — proto je analgetikem první volby v graviditě, u dětí a u pacientů s vředovou chorobou."),
   ("Lebka", "Při vyčerpání glutathionu se hromadí toxický metabolit NAPQI a vzniká centrolobulární jaterní nekróza. ⚠️ Riziko stoupá u chronického alkoholika, malnutrice a při hladovění; potíže se objeví se zpožděním 1–2 dnů, kdy už může být poškození nevratné."),
   ("Antidotum", "N-acetylcystein doplní glutathion; účinný je zvláště v prvních hodinách, proto se podává i při pouhém podezření podle nomogramu."),
   ("Metamizol", "Silné analgetikum se spasmolytickým účinkem (vhodné u kolik). ⚠️ Riziko agranulocytózy a hypotenze při rychlém nitrožilním podání.")],
  "Paracetamol je v mnoha kombinovaných přípravcích proti chřipce — pacient si tak snadno nevědomky podá dvojnásobnou denní dávku. Na to se ptej cíleně.")

S("64", "Nesteroidní antiflogistika",
  "NSA škodí třemi cestami zároveň: ŽALUDEK (ubyde ochranný prostaglandin), LEDVINY (klesne průtok) a SRDCE (roste tlak a riziko příhody).",
  [("🩹", "Analgeticky, antipyreticky, PROTIZÁNĚTLIVĚ"),
   ("🕳️", "Žaludek: eroze a vředy — kryje se IPP"),
   ("🫘", "Ledviny: ↓ průtok, retence sodíku a vody"),
   ("💔", "Koxiby: méně vředů, ale ↑ kardiovaskulární riziko")],
  [("Účinek", "Inhibice COX snižuje tvorbu prostaglandinů — odtud analgezie, antipyreze a protizánětlivý účinek (na rozdíl od paracetamolu)."),
   ("Vřed", "COX-1 tvoří prostaglandiny chránící žaludeční sliznici; jejich úbytek vede k erozím a vředům, které mohou krvácet bez varovné bolesti. U rizikových se přidává inhibitor protonové pumpy."),
   ("Ledvina", "Prostaglandiny udržují průtok ledvinou; NSA ho snižují — retence sodíku a vody, otoky, vzestup tlaku, zhoršení srdečního selhání a riziko akutního poškození ledvin (zvlášť v „trojkombinaci“ s ACE inhibitorem a diuretikem)."),
   ("Srdce", "Selektivní inhibitory COX-2 (koxiby) šetří žaludek, ale zvyšují riziko trombotických příhod. Naproxen má z NSA nejnižší kardiovaskulární riziko."),
   ("Další", "Aspirinem indukované astma, alergie, u dětí s virózou Reyeův syndrom po kyselině acetylsalicylové, ⚠️ v třetím trimestru předčasný uzávěr ductus arteriosus. Ibuprofen ruší antiagregační účinek nízkodávkovaného aspirinu, pokud se podá před ním.")],
  "Nízká dávka kyseliny acetylsalicylové (75–100 mg) blokuje COX-1 v destičkách NEVRATNĚ na celou jejich životnost (7–10 dní) — proto působí antiagregačně, ne protizánětlivě.")

S("65", "Farmakoterapie migrény",
  "Migréna má dvě zcela oddělené léčby: AKUTNÍ záchvat (triptany) a PROFYLAXE (β-blokátor, topiramát). Záměna je klasická chyba.",
  [("⚡", "AKUTNĚ: NSA, při silné atace TRIPTANY"),
   ("🩸", "Triptan = agonista 5-HT1B/1D → vazokonstrikce"),
   ("🛡️", "PROFYLAXE: propranolol, topiramát, amitriptylin"),
   ("🔁", "Nadužívání analgetik → bolest z nadužívání léků")],
  [("Blesk", "Lehký záchvat: NSA (ibuprofen, kyselina acetylsalicylová) nebo paracetamol, nejlépe co nejdříve a s prokinetikem (metoklopramid) proti zvracení a zpomalenému vyprazdňování žaludku."),
   ("Céva", "Triptany (sumatriptan, eletriptan, zolmitriptan) jsou agonisté 5-HT1B/1D — stahují rozšířené intrakraniální cévy a tlumí uvolňování neuropeptidů. ⚠️ Kontraindikace: ischemická choroba srdeční, neléčená hypertenze, prodělaná cévní mozková příhoda, hemiplegická migréna. S SSRI hrozí serotoninový syndrom."),
   ("Štít", "Profylaxe se nasazuje při častých nebo těžkých atakách: β-blokátory (propranolol, metoprolol), topiramát, valproát (⚠️ ne u žen ve fertilním věku), amitriptylin, kandesartan; nově monoklonální protilátky proti CGRP (erenumab) a gepanty."),
   ("Kruh", "Bolest hlavy z nadužívání léků vzniká při užívání analgetik více než ~10–15 dní v měsíci — léčí se vysazením, ne přidáním."),
   ("Ergotamin", "Dnes okrajově — silná a dlouhá vazokonstrikce, riziko ergotismu; nikdy se nekombinuje s triptanem.")],
  "Triptan není analgetikum a nefunguje na tenzní bolest hlavy; naopak profylaktikum neuleví od probíhajícího záchvatu.")
